import test from 'node:test'
import assert from 'node:assert/strict'
import fs from 'node:fs'
import { buildIssueTimeline, buildInterventionTimeline } from '../src/randapp/operational-timeline.js'
const read=(path)=>fs.readFileSync(new URL(`../${path}`,import.meta.url),'utf8')
const component=read('src/randapp/OperationalTimeline.jsx'),css=read('src/randapp/operational-timeline.css'),issues=read('src/randapp/Issues.jsx'),interventions=read('src/randapp/operations/InterventionsView.jsx'),issueData=read('src/issues-data.js')
test('issue timeline is evidence-first and keeps missing timestamps missing',()=>{const e=buildIssueTimeline({status:'waiting',createdAt:1000,createdByName:'Reception',pieceName:'Faretto',pieceDecision:'ordine',pieceDecisionBy:'Mario'});assert.deepEqual(e.map(x=>x.id),['reported','piece-requested']);assert.equal(e[1].at,null);assert.equal(e[1].current,true)})
test('issue timeline uses real technician and completion timestamps when available',()=>{const e=buildIssueTimeline({status:'done',createdAt:1000,technicianRequestedBy:'DCC',technicianRequestedAt:2000,technicianName:'Tecnico',completedAt:3000,completedBy:'Mario',completionPhotoPath:'/done.jpg'});assert.equal(e.find(x=>x.id==='technician').at,2000);assert.equal(e.find(x=>x.id==='completed').media,'/done.jpg')})
test('intervention timeline expands real inventory part timestamps',()=>{const e=buildInterventionTimeline({status:'pending',createdAt:1000,createdBy:'Mario',assignees:[{name:'Luca'}]},[{id:'p1',requestedName:'Lampada',quantity:1,createdAt:'2026-09-24T08:00:00Z',reservedAt:'2026-09-24T08:05:00Z',consumedAt:'2026-09-24T08:30:00Z'}]);const t=e.map(x=>x.title);assert.ok(t.includes('Ricambio richiesto'));assert.ok(t.includes('Ricambio prenotato'));assert.ok(t.includes('Ricambio usato'));assert.equal(e.at(-1).current,true)})
test('timeline UI is shared and replaces duplicate historical cards',()=>{assert.match(component,/data-testid="operational-timeline"/);assert.match(css,/\.rs-operational-timeline__rail::after/);assert.match(issues,/buildIssueTimeline/);assert.doesNotMatch(issues,/rs-note rs-note--done/);assert.match(interventions,/buildInterventionTimeline/);assert.doesNotMatch(interventions,/item\.status==='done'&&<div className="rs-note rs-note--done"/)})
test('issue mapper exposes the persisted technician request time',()=>assert.match(issueData,/technicianRequestedAt:row\.tecnico_richiesto_il\?new Date\(row\.tecnico_richiesto_il\)\.getTime\(\):null/))
