import test from 'node:test'
import assert from 'node:assert/strict'
import { readFile } from 'node:fs/promises'

const read = (path) => readFile(new URL(`../${path}`, import.meta.url), 'utf8')

test('RandAI uses a protected hotel-scoped brain with memory sensors procedures equipment history and manuals', async () => {
  const data = await read('src/randai/randai-data.js')
  const assistant = await read('src/randai/RandAIAssistant.jsx')
  const edge = await read('supabase/functions/randai-assistant/index.ts')
  const knowledgeMigration = await read('supabase/migrations/20260829080500_randai_knowledge_brain.sql')
  const manualMigration = await read('supabase/migrations/20260829082000_randai_manual_knowledge.sql')
  const memoryMigration = await read('supabase/migrations/20260829090000_randai_verified_memory.sql')
  const sensorMigration = await read('supabase/migrations/20260829120000_randai_sensor_context.sql')

  assert.match(data, /functions\.invoke\('randai-assistant'/)
  assert.match(data, /hotel_id: hotelId/)
  assert.match(data, /sensors:/)
  assert.match(data, /memory:/)
  assert.match(edge, /hotel_memberships/)
  assert.match(edge, /randai_search_memory/)
  assert.match(edge, /randai_sensor_context/)
  assert.match(edge, /\.eq\("hotel_id", hotelId\)/)
  assert.match(edge, /\.eq\("status", "approved"\)/)
  assert.match(edge, /randai_equipment_serves/)
  assert.match(edge, /maintenance_issues/)
  assert.match(edge, /interventi/)
  assert.match(edge, /randai_search_document_chunks/)
  assert.match(edge, /Promise\.all/)

  assert.match(assistant, /Memoria RandAI verificata/)
  assert.match(assistant, /Dati live impianto/)
  assert.match(assistant, /Impianto collegato/)
  assert.match(assistant, /Storico RandApp correlato/)
  assert.match(assistant, /Non improvviso/)

  assert.match(knowledgeMigration, /enable row level security/i)
  assert.match(knowledgeMigration, /is_hotel_member\(hotel_id\)/)
  assert.match(knowledgeMigration, /hotelgio-jazz-ac-outdoor-01/)
  assert.match(knowledgeMigration, /4° Jazz/)
  assert.match(manualMigration, /randai_search_document_chunks/)
  assert.match(manualMigration, /grant execute .* service_role/i)
  assert.match(memoryMigration, /randai_memory/)
  assert.match(memoryMigration, /randai_search_memory/)
  assert.match(sensorMigration, /randai_sensor_bindings/)
  assert.match(sensorMigration, /randai_sensor_context/)
  assert.match(sensorMigration, /hotelgio-wine-ac-rooftop-group/)
  assert.match(sensorMigration, /Tutto Wine/)
  assert.match(sensorMigration, /grant execute .* service_role/i)
})
