import { createClient } from "npm:@supabase/supabase-js@2";
import bcrypt from "npm:bcryptjs@2.4.3";

const URL=Deno.env.get("SUPABASE_URL")!, ANON=Deno.env.get("SUPABASE_ANON_KEY")!, SERVICE=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;
const admin=createClient(URL,SERVICE,{auth:{persistSession:false,autoRefreshToken:false}});
const cors={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type","Access-Control-Allow-Methods":"POST, OPTIONS"};
const json=(b:unknown,s=200)=>new Response(JSON.stringify(b),{status:s,headers:{...cors,"Content-Type":"application/json","Cache-Control":"no-store"}});
const ALL_HOTELS=["hotelgio","chocohotel","brigantino"];
const ROLE_VALUES=new Set(["admin","Supremo","Direzione","Direttore Centro Congressi","Portiere Notturno","Responsabile","manutentore","Tecnico esterno","Governante","Capo Governante","Reception","Isola dei Golosi","Ristorante Wine/Jazz","Colazione Jazz"]);
const canonicalRole=(v:unknown)=>{const r=String(v||"Reception").trim();return ROLE_VALUES.has(r)?r:"Reception"};
const validPin=(v:unknown)=>/^\d{4}$/.test(String(v||""));
const normalizeHotels=(v:unknown)=>Array.isArray(v)?[...new Set(v.map(String).filter(h=>ALL_HOTELS.includes(h)))]:[];
const normalizeRolesByHotel=(v:unknown)=>{const out:Record<string,string>={};if(v&&typeof v==="object"&&!Array.isArray(v))for(const [h,r] of Object.entries(v as Record<string,unknown>))if(ALL_HOTELS.includes(h))out[h]=canonicalRole(r);return out};
const normalizeAdminByHotel=(v:unknown)=>{const out:Record<string,boolean>={};if(v&&typeof v==="object"&&!Array.isArray(v))for(const [h,x] of Object.entries(v as Record<string,unknown>))if(ALL_HOTELS.includes(h))out[h]=Boolean(x);return out};
const normalizePhone=(country:string,raw:unknown)=>{const p=(country||"+39").trim();if(!/^\+[1-9]\d{0,3}$/.test(p))throw new Error("Prefisso telefono non valido");if(!raw)return null;const t=String(raw).trim();const full=t.startsWith("+")?`+${t.slice(1).replace(/\D/g,"")}`:`${p}${t.replace(/\D/g,"")}`;if(!/^\+[1-9]\d{7,14}$/.test(full))throw new Error("Numero telefono non valido");return full};

async function caller(req:Request){const token=req.headers.get("authorization")||"";const client=createClient(URL,ANON,{global:{headers:{Authorization:token}},auth:{persistSession:false,autoRefreshToken:false}});const {data,error}=await client.auth.getUser();if(error||!data.user)throw new Error("UNAUTHORIZED");return data.user.id}
async function requireAdmin(req:Request,hotels:string[]){const uid=await caller(req);const wanted=hotels.length?hotels:ALL_HOTELS;const {data,error}=await admin.from("hotel_memberships").select("hotel_id,role,active,can_access_admin").eq("auth_user_id",uid).in("hotel_id",wanted);if(error)throw error;const allowed=new Set((data||[]).filter((r:any)=>r.active&&r.role!=="RandAI"&&(r.role==="admin"||r.can_access_admin)).map((r:any)=>r.hotel_id));if(!wanted.every(h=>allowed.has(h)))throw new Error("FORBIDDEN");return uid}

async function repairLegacyIdentity(legacyId:string){const {data:existing}=await admin.from("profiles").select("auth_user_id,legacy_user_id,is_system_protected").eq("legacy_user_id",legacyId).maybeSingle();if(existing?.auth_user_id)return existing;const {data:legacy,error}=await admin.from("utenti").select("id,nome,ruolo,pin,hotels,puo_admin,department,email,telefono,phone_country_code,deve_cambiare_pin,active,is_system_protected").eq("id",legacyId).maybeSingle();if(error)throw error;if(!legacy)return null;if(legacy.active===false)throw new Error("Utente disattivato");const hotels=normalizeHotels(legacy.hotels);if(!hotels.length)throw new Error("Utente senza strutture abilitate");const role=canonicalRole(legacy.ruolo),can=Boolean(legacy.puo_admin)||role==="admin",internalEmail=legacy.is_system_protected&&legacy.nome==="Randagio"?`system-randagio-${legacy.id}@auth.apicehotel.invalid`:`u-${legacy.id}@auth.apicehotel.invalid`;const password=crypto.randomUUID()+crypto.randomUUID();const {data:created,error:createError}=await admin.auth.admin.createUser({email:internalEmail,password,email_confirm:true,user_metadata:{legacy_user_id:legacy.id,display_name:legacy.nome}});if(createError||!created.user)throw createError||new Error("Creazione identità fallita");const authId=created.user.id;try{const country=String(legacy.phone_country_code||"+39");let e=(await admin.from("profiles").insert({auth_user_id:authId,legacy_user_id:legacy.id,display_name:legacy.nome,department:legacy.department||null,email:legacy.email||null,phone:legacy.telefono||null,phone_country_code:country,active:true,is_system_protected:Boolean(legacy.is_system_protected)})).error;if(e)throw e;if(validPin(legacy.pin)){const hash=await bcrypt.hash(String(legacy.pin),11);e=(await admin.from("auth_pin_credentials").insert({auth_user_id:authId,pin_hash:hash,must_change_pin:Boolean(legacy.deve_cambiare_pin),failed_attempts:0})).error;if(e)throw e}e=(await admin.from("hotel_memberships").insert(hotels.map(hotel_id=>({auth_user_id:authId,hotel_id,role,active:true,can_access_admin:can})))).error;if(e)throw e;return{auth_user_id:authId,legacy_user_id:legacy.id,is_system_protected:Boolean(legacy.is_system_protected)}}catch(e){await admin.auth.admin.deleteUser(authId);throw e}}
async function resolveProfile(id:string){let authId=id;let {data:profile,error}=await admin.from("profiles").select("legacy_user_id,is_system_protected").eq("auth_user_id",authId).maybeSingle();if(error)throw error;if(!profile){const r=await repairLegacyIdentity(id);if(!r)return null;authId=r.auth_user_id;profile={legacy_user_id:r.legacy_user_id,is_system_protected:r.is_system_protected}}return{authId,profile}}

async function readUsers(hotels:string[]){const wanted=hotels.length?hotels:ALL_HOTELS;const {data:legacy,error}=await admin.from("utenti").select("id,nome,ruolo,department,hotels,puo_admin,email,telefono,phone_country_code,active,is_system_protected").overlaps("hotels",wanted).order("is_system_protected",{ascending:false}).order("nome");if(error)throw error;const ids=(legacy||[]).map((u:any)=>u.id);const {data:profiles}=ids.length?await admin.from("profiles").select("auth_user_id,legacy_user_id,display_name,department,email,phone,phone_country_code,active,is_system_protected").in("legacy_user_id",ids):{data:[]};const authIds=(profiles||[]).map((p:any)=>p.auth_user_id);const {data:memberships}=authIds.length?await admin.from("hotel_memberships").select("auth_user_id,hotel_id,role,active,can_access_admin").in("auth_user_id",authIds):{data:[]};const pb=new Map((profiles||[]).map((p:any)=>[p.legacy_user_id,p]));const mb=new Map<string,any[]>();for(const m of memberships||[]){const a=mb.get(m.auth_user_id)||[];a.push(m);mb.set(m.auth_user_id,a)}return(legacy||[]).map((u:any)=>{const p:any=pb.get(u.id),ms=p?mb.get(p.auth_user_id)||[]:[],activeMs=ms.filter((m:any)=>m.active),roles_by_hotel=Object.fromEntries(activeMs.map((m:any)=>[m.hotel_id,m.role])),can_admin_by_hotel=Object.fromEntries(activeMs.map((m:any)=>[m.hotel_id,m.role!=="RandAI"&&(Boolean(m.can_access_admin)||m.role==="admin")])),enabled=activeMs.length?activeMs.map((m:any)=>m.hotel_id):u.hotels,protectedUser=Boolean(u.is_system_protected||p?.is_system_protected),role=activeMs[0]?.role||canonicalRole(u.ruolo);return{id:p?.auth_user_id||u.id,legacy_id:u.id,name:p?.display_name||u.nome,role,roles_by_hotel,department:p?.department??u.department??null,email:p?.email??u.email??null,phone:p?.phone??u.telefono??null,phone_country_code:p?.phone_country_code??u.phone_country_code??"+39",hotels:protectedUser?ALL_HOTELS:enabled,can_admin:protectedUser||Object.values(can_admin_by_hotel).some(Boolean)||(u.ruolo!=="RandAI"&&Boolean(u.puo_admin)),can_admin_by_hotel,active:protectedUser?true:(p?Boolean(p.active):u.active!==false),protected:protectedUser}})}

Deno.serve(async(req:Request)=>{if(req.method==="OPTIONS")return new Response("ok",{headers:cors});if(req.method!=="POST")return json({ok:false,error:"Metodo non consentito"},405);try{const body=await req.json().catch(()=>null),action=String(body?.action||"");if(action==="list"){const hotels=normalizeHotels(body?.hotels);await requireAdmin(req,hotels.length?hotels:ALL_HOTELS);return json({ok:true,users:await readUsers(hotels)})}
if(action==="create"){const name=String(body?.name||"").trim(),hotels=normalizeHotels(body?.hotels),baseRole=canonicalRole(body?.role),rolesByHotel=normalizeRolesByHotel(body?.roles_by_hotel),adminByHotel=normalizeAdminByHotel(body?.can_access_admin_by_hotel),department=body?.department?String(body.department).trim():null,email=body?.email?String(body.email).trim().toLowerCase():null,country=String(body?.phone_country_code||"+39"),phone=normalizePhone(country,body?.phone),pin=String(body?.pin||"");if(!name||!hotels.length||!validPin(pin))return json({ok:false,error:"Nome, struttura e PIN sono obbligatori"},400);await requireAdmin(req,hotels);const legacyId=crypto.randomUUID(),internalEmail=`u-${legacyId}@auth.apicehotel.invalid`,password=crypto.randomUUID()+crypto.randomUUID();const {data:created,error:createError}=await admin.auth.admin.createUser({email:internalEmail,password,email_confirm:true,user_metadata:{legacy_user_id:legacyId,display_name:name}});if(createError||!created.user)throw createError||new Error("Creazione utente fallita");const authId=created.user.id;try{const representative=rolesByHotel[hotels[0]]||baseRole,canAny=hotels.some(h=>adminByHotel[h]??Boolean(body?.can_access_admin)??(rolesByHotel[h]||baseRole)==="admin");let e=(await admin.from("utenti").insert({id:legacyId,nome:name,ruolo:representative,pin:null,hotels,puo_admin:canAny,department,email,telefono:phone,phone_country_code:country,deve_cambiare_pin:false,active:true,is_system_protected:false})).error;if(e)throw e;e=(await admin.from("profiles").insert({auth_user_id:authId,legacy_user_id:legacyId,display_name:name,department,email,phone,phone_country_code:country,active:true,is_system_protected:false})).error;if(e)throw e;const hash=await bcrypt.hash(pin,11);e=(await admin.from("auth_pin_credentials").insert({auth_user_id:authId,pin_hash:hash,must_change_pin:false,failed_attempts:0})).error;if(e)throw e;const rows=hotels.map(h=>{const role=rolesByHotel[h]||baseRole,can=(h in adminByHotel)?adminByHotel[h]:(body?.can_access_admin!==undefined?Boolean(body.can_access_admin):role==="admin");return{auth_user_id:authId,hotel_id:h,role,active:true,can_access_admin:role==="RandAI"?false:(can||role==="admin")}});e=(await admin.from("hotel_memberships").insert(rows)).error;if(e)throw e;return json({ok:true,user:{id:authId,legacy_id:legacyId,name,role:representative,roles_by_hotel:Object.fromEntries(rows.map(r=>[r.hotel_id,r.role])),hotels,active:true,protected:false}})}catch(e){await admin.auth.admin.deleteUser(authId);await admin.from("utenti").delete().eq("id",legacyId);throw e}}
const requestedId=String(body?.auth_user_id||"");if(!requestedId)return json({ok:false,error:"Utente mancante"},400);const resolved=await resolveProfile(requestedId);if(!resolved)return json({ok:false,error:"Utente non trovato"},404);const{authId,profile}=resolved;const {data:currentMemberships,error:currentError}=await admin.from("hotel_memberships").select("hotel_id,role,active,can_access_admin").eq("auth_user_id",authId);if(currentError)throw currentError;const currentHotels=(currentMemberships||[]).filter((m:any)=>m.active).map((m:any)=>m.hotel_id);await requireAdmin(req,currentHotels.length?currentHotels:ALL_HOTELS);if(profile.is_system_protected)return json({ok:false,error:"Randagio è un account di sistema protetto"},403);
if(action==="update"){const nextHotels=body?.hotels!==undefined?normalizeHotels(body.hotels):currentHotels;if(!nextHotels.length)return json({ok:false,error:"Ogni utente deve avere almeno una struttura"},400);await requireAdmin(req,[...new Set([...currentHotels,...nextHotels])]);const profilePatch:Record<string,unknown>={},legacyPatch:Record<string,unknown>={};if(body?.name!==undefined){const n=String(body.name).trim();if(!n)return json({ok:false,error:"Nome non valido"},400);profilePatch.display_name=n;legacyPatch.nome=n}if(body?.department!==undefined){profilePatch.department=body.department?String(body.department).trim():null;legacyPatch.department=profilePatch.department}if(body?.email!==undefined){profilePatch.email=body.email?String(body.email).trim().toLowerCase():null;profilePatch.email_verified=false;legacyPatch.email=profilePatch.email;legacyPatch.email_verified=false}if(body?.phone!==undefined||body?.phone_country_code!==undefined){const c=String(body?.phone_country_code||"+39"),p=normalizePhone(c,body?.phone);profilePatch.phone=p;profilePatch.phone_country_code=c;profilePatch.phone_verified=false;legacyPatch.telefono=p;legacyPatch.phone_country_code=c;legacyPatch.phone_verified=false}
const globalRole=body?.role!==undefined?canonicalRole(body.role):null,rolesByHotel=normalizeRolesByHotel(body?.roles_by_hotel),adminByHotel=normalizeAdminByHotel(body?.can_access_admin_by_hotel),currentMap=new Map((currentMemberships||[]).map((m:any)=>[m.hotel_id,m]));const rows=nextHotels.map(h=>{const prev:any=currentMap.get(h),role=rolesByHotel[h]||globalRole||prev?.role||"Reception",can=(h in adminByHotel)?adminByHotel[h]:(body?.can_access_admin!==undefined?Boolean(body.can_access_admin):Boolean(prev?.can_access_admin));const normalizedRole=canonicalRole(role);return{auth_user_id:authId,hotel_id:h,role:normalizedRole,active:true,can_access_admin:normalizedRole==="RandAI"?false:(can||normalizedRole==="admin")}});legacyPatch.hotels=nextHotels;legacyPatch.ruolo=rows[0].role;legacyPatch.puo_admin=rows.some(r=>r.can_access_admin);if(Object.keys(profilePatch).length){const e=(await admin.from("profiles").update(profilePatch).eq("auth_user_id",authId)).error;if(e)throw e}if(profile.legacy_user_id){const e=(await admin.from("utenti").update(legacyPatch).eq("id",profile.legacy_user_id)).error;if(e)throw e}const removed=currentHotels.filter(h=>!nextHotels.includes(h));if(removed.length){const e=(await admin.from("hotel_memberships").delete().eq("auth_user_id",authId).in("hotel_id",removed)).error;if(e)throw e}const e=(await admin.from("hotel_memberships").upsert(rows,{onConflict:"auth_user_id,hotel_id"})).error;if(e)throw e;return json({ok:true,repaired:requestedId!==authId,auth_user_id:authId,roles_by_hotel:Object.fromEntries(rows.map(r=>[r.hotel_id,r.role]))})}
if(action==="set_pin"){const pin=String(body?.pin||"");if(!validPin(pin))return json({ok:false,error:"PIN non valido"},400);const hash=await bcrypt.hash(pin,11),now=new Date().toISOString();const e=(await admin.from("auth_pin_credentials").upsert({auth_user_id:authId,pin_hash:hash,must_change_pin:Boolean(body?.must_change_pin),failed_attempts:0,locked_until:null,updated_at:now},{onConflict:"auth_user_id"})).error;if(e)throw e;await admin.from("profiles").update({last_pin_change_at:now}).eq("auth_user_id",authId);return json({ok:true})}
if(action==="set_active"){const active=Boolean(body?.active);let e=(await admin.from("profiles").update({active,disabled_at:active?null:new Date().toISOString(),disabled_reason:active?null:(body?.reason?String(body.reason):null)}).eq("auth_user_id",authId)).error;if(e)throw e;e=(await admin.from("hotel_memberships").update({active}).eq("auth_user_id",authId)).error;if(e)throw e;if(profile.legacy_user_id)await admin.from("utenti").update({active}).eq("id",profile.legacy_user_id);return json({ok:true})}
if(action==="hard_delete"){if(profile.legacy_user_id)await admin.from("utenti").delete().eq("id",profile.legacy_user_id);const {error}=await admin.auth.admin.deleteUser(authId);if(error)throw error;return json({ok:true})}
if(action==="tech_link"){const isTech=(currentMemberships||[]).some((m:any)=>m.active&&m.role==="Tecnico esterno");if(!isTech)return json({ok:false,error:"Non è un Tecnico esterno"},400);const {data:existing}=await admin.from("technician_access_tokens").select("token,revoked_at").eq("auth_user_id",authId).maybeSingle();if(existing?.token&&!existing.revoked_at&&!body?.regenerate)return json({ok:true,token:existing.token});const bytes=new Uint8Array(24);crypto.getRandomValues(bytes);const token=Array.from(bytes).map(b=>b.toString(16).padStart(2,"0")).join("");const e=(await admin.from("technician_access_tokens").upsert({auth_user_id:authId,token,revoked_at:null,created_at:new Date().toISOString()},{onConflict:"auth_user_id"})).error;if(e)throw e;return json({ok:true,token})}
return json({ok:false,error:"Azione non valida"},400)}catch(error){const m=error instanceof Error?error.message:"unknown";if(m==="UNAUTHORIZED")return json({ok:false,error:"Non autenticato"},401);if(m==="FORBIDDEN")return json({ok:false,error:"Permesso amministratore richiesto"},403);console.error("admin-users",m);return json({ok:false,error:m||"Errore gestione utenti"},500)}});