name: randui-preview
region: fra
static_sites:
  - name: randui
    github:
      repo: Apicehotel/Apicehotel-Manutenzione
      branch: ${OCEAN_GITHUB_BRANCH}
      deploy_on_push: false
    source_dir: /
    environment_slug: node-js
    build_command: npm ci && npm run build
    output_dir: dist
    index_document: index.html
    catchall_document: index.html
    routes:
      - path: /
