import { createClient } from "npm:@supabase/supabase-js@2";
import bcrypt from "npm:bcryptjs@2.4.3";

const URL=Deno.env.get("SUPABASE_URL")!, ANON=Deno.env.get("SUPABASE_ANON_KEY")!, SERVICE=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;
const admin=createClient(URL,SERVICE,{auth:{persistSession:false,autoRefreshToken:false}});
const cors={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type","Access-Control-Allow-Methods":"POST, OPTIONS"};
const json=(body:unknown,status=200)=>new Response(JSON.stringify(body),{status,headers:{...cors,"Content-Type":"application/json","Cache-Control":"no-store"}});
const ALL_HOTELS=["hotelgio","chocohotel","brigantino"];
const validUsername=(v:unknown)=>/^[A-Za-z0-9._-]{3,32}$/.test(String(v||""));
const validPassword=(v:unknown)=>/^[A-Za-z0-9]{6,12}$/.test(String(v||""));
const normalizeHotels=(v:unknown)=>Array.isArray(v)?[...new Set(v.map(String).filter(h=>ALL_HOTELS.includes(h)))]:[];

async function caller(req:Request){const token=req.headers.get("authorization")||"";const client=createClient(URL,ANON,{global:{headers:{Authorization:token}},auth:{persistSession:false,autoRefreshToken:false}});const {data,error}=await client.auth.getUser();if(error||!data.user)throw new Error("UNAUTHORIZED");return data.user.id}
async function requireRandAI(req:Request){const uid=await caller(req);const {data,error}=await admin.from("hotel_memberships").select("hotel_id,role,active,can_access_admin").eq("auth_user_id",uid).eq("active",true);if(error)throw error;const allowed=(data||[]).filter((r:any)=>r.role==="RandAI"&&r.can_access_admin);if(!allowed.length)throw new Error("FORBIDDEN");return{uid,hotels:allowed.map((r:any)=>String(r.hotel_id))}}

async function ensureIdentity(credential:any,legacy:any){let authId=credential.auth_user_id as string|undefined;if(authId)return authId;const internalEmail=`randai-${legacy.id}@auth.apicehotel.invalid`;const password=crypto.randomUUID()+crypto.randomUUID();const {data:created,error:createError}=await admin.auth.admin.createUser({email:internalEmail,password,email_confirm:true,user_metadata:{legacy_user_id:legacy.id,display_name:legacy.nome,randai:true}});if(createError||!created.user)throw createError||new Error("Creazione identità RandAI fallita");authId=created.user.id;try{let e=(await admin.from("profiles").upsert({auth_user_id:authId,legacy_user_id:legacy.id,display_name:legacy.nome,department:legacy.department||null,email:legacy.email||null,phone:legacy.telefono||null,phone_country_code:legacy.phone_country_code||"+39",active:true,is_system_protected:false,updated_at:new Date().toISOString()},{onConflict:"auth_user_id"})).error;if(e)throw e;const hotels=normalizeHotels(legacy.hotels);e=(await admin.from("hotel_memberships").upsert(hotels.map((hotel_id:string)=>({auth_user_id:authId,hotel_id,role:"RandAI",active:true,can_access_admin:true})),{onConflict:"auth_user_id,hotel_id"})).error;if(e)throw e;e=(await admin.from("randai_credentials").update({auth_user_id:authId,updated_at:new Date().toISOString()}).eq("id",credential.id)).error;if(e)throw e;return authId}catch(error){await admin.auth.admin.deleteUser(authId);throw error}}

async function login(username:string,password:string){const {data:credential,error}=await admin.from("randai_credentials").select("id,legacy_user_id,auth_user_id,password_hash,must_change_password,failed_attempts,locked_until").ilike("username",username).maybeSingle();if(error)throw error;if(!credential)return json({ok:false,error:"Credenziali non valide"},401);if(credential.locked_until&&new Date(credential.locked_until).getTime()>Date.now())return json({ok:false,error:"Troppi tentativi. Riprova più tardi."},429);const valid=await bcrypt.compare(password,credential.password_hash);if(!valid){const failures=Number(credential.failed_attempts||0)+1,patch:any={failed_attempts:failures,updated_at:new Date().toISOString()};if(failures>=5){patch.failed_attempts=0;patch.locked_until=new Date(Date.now()+10*60*1000).toISOString()}await admin.from("randai_credentials").update(patch).eq("id",credential.id);return json({ok:false,error:"Credenziali non valide"},401)}const {data:legacy,error:legacyError}=await admin.from("utenti").select("id,nome,ruolo,hotels,department,email,telefono,phone_country_code,active").eq("id",credential.legacy_user_id).maybeSingle();if(legacyError||!legacy||legacy.active===false||legacy.ruolo!=="RandAI")return json({ok:false,error:"Accesso RandAI non disponibile"},403);const authId=await ensureIdentity(credential,legacy);const internalEmail=`randai-${legacy.id}@auth.apicehotel.invalid`;const tempPassword=crypto.randomUUID()+crypto.randomUUID();const {error:updateError}=await admin.auth.admin.updateUserById(authId,{password:tempPassword});if(updateError)throw updateError;const client=createClient(URL,ANON,{auth:{persistSession:false,autoRefreshToken:false}});const {data:signed,error:signError}=await client.auth.signInWithPassword({email:internalEmail,password:tempPassword});if(signError||!signed.session)throw signError||new Error("Sessione non disponibile");await admin.from("randai_credentials").update({failed_attempts:0,locked_until:null,updated_at:new Date().toISOString()}).eq("id",credential.id);return json({ok:true,session:{access_token:signed.session.access_token,refresh_token:signed.session.refresh_token,expires_at:signed.session.expires_at},user:{id:authId,name:legacy.nome,role:"RandAI",username,hotels:normalizeHotels(legacy.hotels),must_change_password:Boolean(credential.must_change_password)}})}

async function listUsers(req:Request){const access=await requireRandAI(req);const {data:memberships,error}=await admin.from("hotel_memberships").select("auth_user_id,hotel_id,role,active").eq("role","RandAI").eq("active",true).in("hotel_id",access.hotels);if(error)throw error;const ids=[...new Set((memberships||[]).map((x:any)=>x.auth_user_id))];if(!ids.length)return json({ok:true,users:[]});const [{data:profiles},{data:creds}]=await Promise.all([admin.from("profiles").select("auth_user_id,display_name,active").in("auth_user_id",ids),admin.from("randai_credentials").select("auth_user_id,username,must_change_password,updated_at").in("auth_user_id",ids)]);const byProfile=new Map((profiles||[]).map((x:any)=>[x.auth_user_id,x])),byCred=new Map((creds||[]).map((x:any)=>[x.auth_user_id,x]));const hotelsBy=new Map<string,string[]>();for(const row of memberships||[]){const list=hotelsBy.get(row.auth_user_id)||[];if(!list.includes(row.hotel_id))list.push(row.hotel_id);hotelsBy.set(row.auth_user_id,list)}return json({ok:true,users:ids.map((id:any)=>({id,name:byProfile.get(id)?.display_name||"RandAI",username:byCred.get(id)?.username||"",hotels:hotelsBy.get(id)||[],active:byProfile.get(id)?.active!==false,must_change_password:Boolean(byCred.get(id)?.must_change_password)}))})}

async function createUser(req:Request,body:any){const access=await requireRandAI(req);const name=String(body?.name||"").trim(),username=String(body?.username||"").trim(),password=String(body?.password||""),hotels=normalizeHotels(body?.hotels);if(!name||!validUsername(username)||!validPassword(password)||!hotels.length)return json({ok:false,error:"Nome, username, password e struttura sono obbligatori"},400);if(!hotels.every(h=>access.hotels.includes(h)))return json({ok:false,error:"Struttura non autorizzata"},403);const {data:existing}=await admin.from("randai_credentials").select("id").ilike("username",username).maybeSingle();if(existing)return json({ok:false,error:"Username già utilizzato"},409);const legacyId=crypto.randomUUID(),internalEmail=`randai-${legacyId}@auth.apicehotel.invalid`,tempPassword=crypto.randomUUID()+crypto.randomUUID();const {data:created,error:createError}=await admin.auth.admin.createUser({email:internalEmail,password:tempPassword,email_confirm:true,user_metadata:{legacy_user_id:legacyId,display_name:name,randai:true}});if(createError||!created.user)throw createError||new Error("Creazione utente fallita");const authId=created.user.id;try{let e=(await admin.from("utenti").insert({id:legacyId,nome:name,ruolo:"RandAI",pin:null,hotels,puo_admin:true,deve_cambiare_pin:false,active:true,is_system_protected:false})).error;if(e)throw e;e=(await admin.from("profiles").insert({auth_user_id:authId,legacy_user_id:legacyId,display_name:name,active:true,is_system_protected:false})).error;if(e)throw e;e=(await admin.from("hotel_memberships").insert(hotels.map(hotel_id=>({auth_user_id:authId,hotel_id,role:"RandAI",active:true,can_access_admin:true})))).error;if(e)throw e;const hash=await bcrypt.hash(password,11);e=(await admin.from("randai_credentials").insert({legacy_user_id:legacyId,auth_user_id:authId,username,password_hash:hash,must_change_password:true,failed_attempts:0})).error;if(e)throw e;return json({ok:true,user:{id:authId,name,username,hotels,must_change_password:true}})}catch(error){await admin.auth.admin.deleteUser(authId);await admin.from("utenti").delete().eq("id",legacyId);throw error}}

async function changePassword(req:Request,password:string){const uid=await caller(req);if(!validPassword(password))return json({ok:false,error:"La password deve essere alfanumerica e lunga da 6 a 12 caratteri"},400);const {data:credential,error}=await admin.from("randai_credentials").select("id").eq("auth_user_id",uid).maybeSingle();if(error)throw error;if(!credential)return json({ok:false,error:"Profilo RandAI non trovato"},404);const hash=await bcrypt.hash(password,11);const e=(await admin.from("randai_credentials").update({password_hash:hash,must_change_password:false,failed_attempts:0,locked_until:null,updated_at:new Date().toISOString()}).eq("id",credential.id)).error;if(e)throw e;return json({ok:true})}

Deno.serve(async(req:Request)=>{if(req.method==="OPTIONS")return new Response("ok",{headers:cors});if(req.method!=="POST")return json({ok:false,error:"Metodo non consentito"},405);try{const body=await req.json().catch(()=>null),action=String(body?.action||"login");if(action==="login"){const username=String(body?.username||"").trim(),password=String(body?.password||"");if(!validUsername(username)||!validPassword(password))return json({ok:false,error:"Credenziali non valide"},400);return await login(username,password)}if(action==="list_users")return await listUsers(req);if(action==="create_user")return await createUser(req,body);if(action==="change_password")return await changePassword(req,String(body?.password||""));return json({ok:false,error:"Azione non valida"},400)}catch(error){const m=error instanceof Error?error.message:"unknown";if(m==="UNAUTHORIZED")return json({ok:false,error:"Sessione non valida"},401);if(m==="FORBIDDEN")return json({ok:false,error:"Accesso RandAI non consentito"},403);console.error("randai-auth",m);return json({ok:false,error:"Errore temporaneo RandAI"},500)}});
