import { useEffect, useState } from 'react'
import { deleteBookingRow, fetchBookings, subscribeBookings } from '../sale-data.js'
import { fetchSaleRooms, subscribeSaleRooms } from '../sale-config-data.js'
import { fetchSaleClients, fetchSaleLayouts } from '../sale-directory-data.js'
import { Icon } from './ui.jsx'
import PlanningDateNavigator from './planning/PlanningDateNavigator.jsx'
import SaleBookingCard from './planning/SaleBookingCard.jsx'
import SaleBookingForm from './planning/SaleBookingForm.jsx'
import SaleRoomConfigSheet from './planning/SaleRoomConfigSheet.jsx'
import { addDays, canManageSalePlanning, canOperateSalePlanning, dayLabel, iso } from './planning/sale-utils.js'

export { canManageSalePlanning, canOperateSalePlanning } from './planning/sale-utils.js'

function Metric({value,label,tone='normal'}){const color=tone==='done'?'var(--rs-ok)':tone==='finish'?'var(--rs-warn)':'var(--rs-text)';return <div style={{border:'1px solid var(--rs-line)',borderRadius:14,padding:'10px 8px',background:'var(--rs-surface)',textAlign:'center'}}><b style={{display:'block',fontFamily:'Sora',fontSize:'1.15rem',color}}>{value}</b><small style={{color:'var(--rs-text-3)'}}>{label}</small></div>}

export default function PlanningSaleSimple({hotel,user,openRequest=0}){
  const [bookings,setBookings]=useState([]),[rooms,setRooms]=useState([]),[clients,setClients]=useState([]),[layouts,setLayouts]=useState([]),[anchor,setAnchor]=useState(()=>new Date()),[view,setView]=useState('giorno'),[creating,setCreating]=useState(false),[editing,setEditing]=useState(null),[configOpen,setConfigOpen]=useState(false),[error,setError]=useState('')
  const director=canManageSalePlanning(user),allowed=canOperateSalePlanning(user)
  const load=async()=>{if(!allowed)return;try{setError('');const tasks=[fetchBookings(hotel.id),fetchSaleRooms(hotel.id,{includeInactive:director})];if(director)tasks.push(fetchSaleClients(hotel.id),fetchSaleLayouts(hotel.id));const data=await Promise.all(tasks);setBookings(data[0].items||[]);setRooms(data[1]||[]);if(director){setClients(data[2]||[]);setLayouts(data[3]||[])}}catch(err){setError(err?.message||'Planning sale non disponibile')}}
  useEffect(()=>{if(!allowed)return;load();const offBookings=subscribeBookings(hotel.id,load),offRooms=subscribeSaleRooms(hotel.id,load);return()=>{offBookings?.();offRooms?.()}},[hotel.id,allowed,director])
  useEffect(()=>{if(openRequest&&director)setCreating(true)},[openRequest,director])
  if(!allowed)return <p style={{margin:0,color:'var(--rs-text-3)'}}>Planning sale non disponibile per questo ruolo.</p>
  const count=view==='giorno'?1:7,days=Array.from({length:count},(_,i)=>addDays(anchor,i)),today=iso(),todayRows=bookings.filter(b=>(b.prepDate||b.dateFrom||b.date)===today),stats={today:todayRows.filter(b=>b.status!=='done').length,finish:todayRows.filter(b=>b.status==='da_finire').length,done:todayRows.filter(b=>b.status==='done').length}
  const remove=async b=>{if(!director||!window.confirm(`Eliminare la prenotazione di “${b.client}”?`))return;await deleteBookingRow(b.id,hotel.id);await load()}
  const periodLabel=view==='giorno'?dayLabel(anchor):`${dayLabel(days[0])} – ${dayLabel(days[6])}`
  return <section style={{display:'grid',gap:14}}><div style={{padding:'10px 12px',border:'1px solid var(--rs-line)',borderRadius:14,background:'var(--rs-surface-2)'}}><strong>Preparazioni sale</strong><small style={{display:'block',marginTop:3,color:'var(--rs-text-3)'}}>Qui compaiono nel giorno stabilito dal Direttore Centro Congressi. Le date evento restano nel calendario della schermata Planning.</small></div><div style={{display:'grid',gridTemplateColumns:'repeat(3,minmax(0,1fr))',gap:8}}><Metric value={stats.today} label="Oggi"/><Metric value={stats.finish} label="Da finire" tone="finish"/><Metric value={stats.done} label="Fatti oggi" tone="done"/></div>{director&&<div style={{display:'grid',gap:8}}><button type="button" className="rs-btn rs-btn--ghost" onClick={()=>setConfigOpen(true)}><Icon name="gear"/> Configura sale</button></div>}<div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:7}}><button type="button" className={`rs-btn ${view==='giorno'?'rs-btn--primary':'rs-btn--ghost'}`} onClick={()=>setView('giorno')}>Giorno</button><button type="button" className={`rs-btn ${view==='settimana'?'rs-btn--primary':'rs-btn--ghost'}`} onClick={()=>setView('settimana')}>Settimana</button></div><PlanningDateNavigator label={periodLabel} onPrevious={()=>setAnchor(d=>addDays(d,view==='giorno'?-1:-7))} onNext={()=>setAnchor(d=>addDays(d,view==='giorno'?1:7))} onToday={()=>setAnchor(new Date())}/>{error&&<p style={{margin:0,color:'#e35d6a'}}>{error}</p>}<div style={{display:'grid',gap:14}}>{days.map(day=>{const date=iso(day),list=bookings.filter(b=>(b.prepDate||b.dateFrom||b.date)===date);return <section key={date} style={{display:'grid',gap:9}}><h3 style={{margin:'5px 0 0',fontFamily:'Sora',color:date===today?'var(--rs-ok)':'var(--rs-text)'}}>{dayLabel(day)}{date===today?' · oggi':''}</h3>{list.length?list.map(b=><div key={b.id} style={{display:'grid',gap:5}}><SaleBookingCard booking={b} user={user} onRefresh={load} onEdit={setEditing}/>{director&&<button type="button" onClick={()=>remove(b)} style={{justifySelf:'end',border:0,background:'transparent',color:'#e35d6a'}}>Elimina</button>}</div>):<p style={{margin:0,color:'var(--rs-text-3)'}}>Nessuna sala da preparare.</p>}</section>})}</div><SaleBookingForm open={creating||Boolean(editing)} onClose={()=>{setCreating(false);setEditing(null)}} hotel={hotel} user={user} bookings={bookings} rooms={rooms} clients={clients} layouts={layouts} initial={editing} onSaved={load} onDirectoryChanged={load}/>{director&&<SaleRoomConfigSheet open={configOpen} onClose={()=>setConfigOpen(false)} hotel={hotel} rooms={rooms} onSaved={load}/>}</section>
}
