import { useCallback, useEffect, useMemo, useState } from 'react'
import { fetchPlanningWork, subscribePlanningWork } from '../planning-work-data.js'
import { fetchBookings, subscribeBookings } from '../sale-data.js'
import { Icon, Spinner } from './ui.jsx'
import PlanningWorkSimple from './PlanningWorkSimple.jsx'
import PlanningSaleSimple, { canOperateSalePlanning } from './PlanningSaleSimple.jsx'
import PlannedCreateSheet from './PlannedCreateSheet.jsx'

const WD=['Dom','Lun','Mar','Mer','Gio','Ven','Sab']
const MONTHS=['gen','feb','mar','apr','mag','giu','lug','ago','set','ott','nov','dic']
const SHIFTS={mattina:'Mattina',pomeriggio:'Pomeriggio',tutto_giorno:'Giornata intera'}
const isoDay=(value=new Date())=>{const d=new Date(value);return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}
const addDays=(value,n)=>{const d=new Date(value);d.setDate(d.getDate()+n);return d}
const startOfWeek=(value)=>{const d=new Date(value);const offset=(d.getDay()+6)%7;d.setDate(d.getDate()-offset);d.setHours(12,0,0,0);return d}
const shortDate=(value)=>`${value.getDate()} ${MONTHS[value.getMonth()]}`
const eventOnDay=(item,date)=>(item.dateFrom||item.date)<=date&&(item.dateTo||item.date)>=date
function Metric({value,label,tone='normal'}){const color=tone==='done'?'var(--rs-ok)':tone==='finish'?'var(--rs-warn)':'var(--rs-text-2)';return <div style={{width:54,height:54,border:'1px solid var(--rs-line)',borderRadius:14,background:'var(--rs-surface-2)',display:'grid',placeItems:'center',alignContent:'center'}}><b style={{fontFamily:'Sora',fontSize:'1.05rem',color}}>{value}</b><small style={{fontSize:'.58rem',color:'var(--rs-text-2)',marginTop:4}}>{label}</small></div>}
function PlanningChoice({active,icon,title,stats,onClick}){return <button type="button" onClick={onClick} aria-pressed={active} style={{minWidth:0,textAlign:'left',color:'var(--rs-text)',border:`1px solid ${active?'var(--rs-line-strong)':'var(--rs-line)'}`,background:active?'var(--rs-surface-3)':'var(--rs-surface)',borderRadius:18,padding:12,boxShadow:active?'var(--rs-glow)':'var(--rs-shadow)'}}><div style={{display:'flex',alignItems:'center',gap:8,marginBottom:10}}><span style={{width:34,height:34,borderRadius:11,display:'grid',placeItems:'center',background:'var(--rs-surface-2)',color:'var(--rs-cyan)'}}><Icon name={icon}/></span><strong style={{fontFamily:'Sora',fontSize:'.9rem'}}>{title}</strong><span style={{marginLeft:'auto',color:'var(--rs-text-3)'}}>›</span></div><div style={{display:'flex',gap:6,justifyContent:'space-between'}}><Metric value={stats.today} label="Oggi"/><Metric value={stats.finish} label="Da finire" tone="finish"/><Metric value={stats.done} label="Fatti oggi" tone="done"/></div></button>}

function SaleEventCalendar({bookings}){
  const [anchor,setAnchor]=useState(()=>new Date())
  const today=isoDay(),weekStart=startOfWeek(anchor),days=Array.from({length:7},(_,i)=>addDays(weekStart,i))
  const weekEnd=days[6]
  return <section style={{border:'1px solid var(--rs-line)',borderRadius:18,padding:14,background:'var(--rs-surface)',display:'grid',gap:12}}>
    <header style={{display:'flex',alignItems:'flex-start',gap:10}}><div style={{minWidth:0,flex:1}}><strong style={{fontFamily:'Sora',fontSize:'1rem'}}>Calendario sale</strong><p style={{margin:'4px 0 0',color:'var(--rs-text-3)',fontSize:'.78rem'}}>Quando le sale sono occupate: qui conta la data dell'evento.</p></div><button type="button" className="rs-btn rs-btn--ghost" onClick={()=>setAnchor(new Date())}>Oggi</button></header>
    <div style={{display:'grid',gridTemplateColumns:'44px minmax(0,1fr) 44px',gap:7,alignItems:'center'}}><button type="button" className="rs-btn rs-btn--ghost" onClick={()=>setAnchor(d=>addDays(d,-7))}>‹</button><div style={{textAlign:'center',fontWeight:800,color:'var(--rs-text-2)'}}>{shortDate(days[0])} – {shortDate(weekEnd)}</div><button type="button" className="rs-btn rs-btn--ghost" onClick={()=>setAnchor(d=>addDays(d,7))}>›</button></div>
    <div style={{display:'grid',gap:7}}>{days.map(day=>{const date=isoDay(day),rows=bookings.filter(b=>eventOnDay(b,date));return <div key={date} style={{display:'grid',gridTemplateColumns:'62px minmax(0,1fr)',gap:8,alignItems:'start'}}><div style={{paddingTop:8,textAlign:'center'}}><strong style={{display:'block',fontSize:'.72rem',color:date===today?'var(--rs-cyan)':'var(--rs-text-2)'}}>{WD[day.getDay()]}</strong><span style={{display:'grid',placeItems:'center',width:34,height:34,margin:'3px auto 0',borderRadius:99,background:date===today?'var(--rs-grad-primary)':'var(--rs-surface-2)',color:date===today?'white':'var(--rs-text)',fontWeight:800}}>{day.getDate()}</span></div><div style={{display:'grid',gap:6,minHeight:50,padding:'6px 0 8px',borderBottom:'1px solid var(--rs-line)'}}>{rows.length?rows.map(b=><article key={`${b.id}-${date}`} style={{border:'1px solid var(--rs-line)',borderLeft:'4px solid var(--rs-cyan)',borderRadius:13,padding:'9px 10px',background:'var(--rs-surface-2)',display:'grid',gap:2}}><div style={{display:'flex',gap:8,alignItems:'baseline'}}><strong style={{minWidth:0,flex:1}}>{b.room}</strong><small style={{color:'var(--rs-text-3)',whiteSpace:'nowrap'}}>{SHIFTS[b.shift]||b.shift}</small></div><span style={{fontSize:'.78rem',color:'var(--rs-text-2)'}}>{b.client}{b.layout?` · ${b.layout}`:''}{b.pax?` · ${b.pax} PAX`:''}</span>{b.dateTo&&b.dateTo!==b.dateFrom&&<small style={{color:'var(--rs-text-3)'}}>Evento {b.dateFrom} → {b.dateTo}</small>}</article>):<span style={{padding:'9px 2px',color:'var(--rs-text-3)',fontSize:'.78rem'}}>Nessuna sala occupata.</span>}</div></div>})}</div>
  </section>
}

export default function PlanningHub({hotel,user,createRequest=null}){
  const [section,setSection]=useState(null),[work,setWork]=useState([]),[bookings,setBookings]=useState([]),[loading,setLoading]=useState(true),[workCreateSignal,setWorkCreateSignal]=useState(0),[saleCreateSignal,setSaleCreateSignal]=useState(0),[interventionCreateOpen,setInterventionCreateOpen]=useState(false)
  const canSeeSale=canOperateSalePlanning(user)
  const load=useCallback(async()=>{setLoading(true);try{const workPromise=fetchPlanningWork(hotel.id);const salesPromise=canSeeSale?fetchBookings(hotel.id):Promise.resolve({items:[]});const [workItems,sales]=await Promise.all([workPromise,salesPromise]);setWork(workItems||[]);setBookings(sales.items||[])}finally{setLoading(false)}},[hotel.id,canSeeSale])
  useEffect(()=>{setSection(null);load();const offWork=subscribePlanningWork(hotel.id,load);const offSales=canSeeSale?subscribeBookings(hotel.id,load):null;return()=>{offWork?.();offSales?.()}},[hotel.id,load,canSeeSale])
  useEffect(()=>{if(!createRequest?.nonce)return;if(createRequest.kind==='work'){let source='planning-work';try{source=sessionStorage.getItem('randapp.insert-source')||source;sessionStorage.removeItem('randapp.insert-source')}catch{}if(source==='intervention'){setSection(null);setInterventionCreateOpen(true)}else{setSection('work');setWorkCreateSignal(n=>n+1)}}if(createRequest.kind==='sale'&&canSeeSale){setSection('sale');setSaleCreateSignal(n=>n+1)}},[createRequest?.nonce,createRequest?.kind,canSeeSale])
  const today=isoDay(),todayWork=useMemo(()=>work.filter(item=>item.date===today),[work,today]),todayEventSales=useMemo(()=>bookings.filter(item=>eventOnDay(item,today)),[bookings,today]),todayPrepSales=useMemo(()=>bookings.filter(item=>(item.prepDate||item.dateFrom||item.date)===today),[bookings,today])
  const workStats={today:todayWork.filter(x=>x.status!=='done').length,finish:todayWork.filter(x=>x.status==='da_finire').length,done:todayWork.filter(x=>x.status==='done').length}
  const saleStats={today:todayPrepSales.filter(x=>x.status!=='done').length,finish:todayPrepSales.filter(x=>x.status==='da_finire').length,done:todayPrepSales.filter(x=>x.status==='done').length}
  if(loading)return <Spinner label="Carico planning…"/>
  return <div data-testid="planning-hub">
    <div className="rs-page-title"><div><h1>Planning</h1><p>{section?(section==='sale'?'Preparazioni operative delle sale.':'Calendario operativo.'):'Lavori e sale restano separati.'}</p></div>{section&&<button type="button" className="rs-btn rs-btn--ghost" onClick={()=>setSection(null)}>‹ Oggi</button>}</div>
    <div style={{display:'grid',gridTemplateColumns:canSeeSale?'repeat(2,minmax(0,1fr))':'1fr',gap:10,marginBottom:16}}><PlanningChoice active={section==='work'} icon="wrench" title="Planning lavori" stats={workStats} onClick={()=>setSection('work')}/>{canSeeSale&&<PlanningChoice active={section==='sale'} icon="calendar" title="Planning sale" stats={saleStats} onClick={()=>setSection('sale')}/>}</div>
    {!section?<div style={{display:'grid',gap:12}}><div style={{border:'1px solid var(--rs-line)',borderRadius:16,padding:14,background:'var(--rs-surface)'}}><strong>Lavori oggi</strong><p style={{margin:'6px 0 0',color:'var(--rs-text-2)'}}>{todayWork.length?`${todayWork.length} lavor${todayWork.length===1?'o':'i'} nel planning.`:'Nessun lavoro previsto oggi.'}</p></div>{canSeeSale&&<><div style={{border:'1px solid var(--rs-line)',borderRadius:16,padding:14,background:'var(--rs-surface)'}}><strong>Sale oggi</strong><p style={{margin:'6px 0 0',color:'var(--rs-text-2)'}}>{todayEventSales.length?`${todayEventSales.length} attività/prenotazioni in corso oggi.`:'Nessuna sala occupata oggi.'}</p></div><SaleEventCalendar bookings={bookings}/></>}</div>:section==='work'?<PlanningWorkSimple hotel={hotel} user={user} openRequest={workCreateSignal}/>:canSeeSale?<PlanningSaleSimple hotel={hotel} user={user} openRequest={saleCreateSignal}/>:null}
    <PlannedCreateSheet open={interventionCreateOpen} onClose={()=>setInterventionCreateOpen(false)} hotel={hotel} user={user} onSaved={()=>setInterventionCreateOpen(false)}/>
  </div>
}
