import { useEffect, useMemo, useState } from 'react'
import { ROLES } from '../config.js'
import { canSendReminder, canEditReminder, canDeleteReminder, createReminder, deleteReminder, fetchReminders, subscribeReminders, updateReminder, updateReminderWithPhoto } from '../reminders-data.js'
import { Button, Card, Field, Icon, EmptyState, Spinner } from './ui.jsx'
import './reminders.css'

const WEEKDAYS = [['mon','Lun'],['tue','Mar'],['wed','Mer'],['thu','Gio'],['fri','Ven'],['sat','Sab'],['sun','Dom']]
const repeatLabel = (r) => r.repeat_kind === 'once' ? 'Una volta' : r.repeat_kind === 'daily' ? 'Ogni giorno' : r.repeat_kind === 'weekly' ? 'Giorni selezionati' : 'Ogni mese'
const today = () => new Date().toISOString().slice(0,10)
const uniqSorted = (list) => [...new Set(list.filter(Boolean))].sort()
const emptyForm = () => ({ text:'', roles:['manutentore'], repeat:'once', weekdays:[], times:['09:00'], startDate:today(), endDate:'', photo:null, removePhoto:false })

export default function RemindersView({ hotel, user }) {
  const [items,setItems]=useState([]),[loading,setLoading]=useState(true),[creating,setCreating]=useState(false),[saving,setSaving]=useState(false),[message,setMessage]=useState('')
  const [editing,setEditing]=useState(null),[rolePickerOpen,setRolePickerOpen]=useState(false),[form,setForm]=useState(emptyForm())
  const allowed=canSendReminder(user), editAllowed=canEditReminder(user), deleteAllowed=canDeleteReminder(user)
  const load=async()=>{try{setItems(await fetchReminders(hotel.id))}catch(e){setMessage(e?.message||'Errore caricamento')}finally{setLoading(false)}}
  useEffect(()=>{setLoading(true);load();const off=subscribeReminders(hotel.id,load);return()=>off?.()},[hotel.id])
  const photoPreview=useMemo(()=>form.photo?URL.createObjectURL(form.photo):null,[form.photo])
  useEffect(()=>()=>{if(photoPreview)URL.revokeObjectURL(photoPreview)},[photoPreview])
  const activeCount=useMemo(()=>items.filter(x=>x.active).length,[items])
  const patch=(changes)=>setForm(current=>({...current,...changes}))
  const toggleRole=(role)=>patch({roles:form.roles.includes(role)?form.roles.filter(x=>x!==role):[...form.roles,role]})
  const allRolesSelected=ROLES.length>0&&ROLES.every(role=>form.roles.includes(role))
  const toggleAllRoles=()=>patch({roles:allRolesSelected?[]:[...ROLES]})
  const toggleDay=(day)=>patch({weekdays:form.weekdays.includes(day)?form.weekdays.filter(x=>x!==day):[...form.weekdays,day]})
  const addTime=()=>patch({times:[...form.times,'12:00']})
  const setTime=(index,value)=>patch({times:form.times.map((x,i)=>i===index?value:x)})
  const removeTime=(index)=>patch({times:form.times.filter((_,i)=>i!==index)})
  const closeForm=()=>{setCreating(false);setEditing(null);setRolePickerOpen(false);setForm(emptyForm())}
  const openNew=()=>{setEditing(null);setForm(emptyForm());setCreating(true);setRolePickerOpen(false);setMessage('')}
  const openEdit=(item)=>{if(!editAllowed)return;setEditing(item);setCreating(true);setRolePickerOpen(false);setMessage('');setForm({text:item.message||'',roles:item.target_roles||[],repeat:item.repeat_kind||'once',weekdays:item.weekdays||[],times:item.times?.length?item.times:['09:00'],startDate:item.start_date||today(),endDate:item.end_date||'',photo:null,removePhoto:false})}
  const save=async(e)=>{e.preventDefault();if(editing&&!editAllowed)return setMessage('Il tuo ruolo non può modificare promemoria');if(!form.text.trim())return setMessage('Inserisci il testo del promemoria');if(!form.roles.length)return setMessage('Scegli almeno un ruolo destinatario');if(!form.times.length)return setMessage('Aggiungi almeno un orario');if(form.repeat==='weekly'&&!form.weekdays.length)return setMessage('Scegli almeno un giorno della settimana');setSaving(true);setMessage('');const payload={message:form.text.trim(),target_roles:form.roles,repeat_kind:form.repeat,weekdays:form.repeat==='weekly'?form.weekdays:[],month_day:form.repeat==='monthly'?Number(form.startDate.slice(8,10)):null,times:uniqSorted(form.times),start_date:form.startDate,end_date:form.endDate||null};try{if(editing){await updateReminderWithPhoto(editing,payload,form.photo,form.removePhoto);setMessage('Promemoria modificato')}else{await createReminder({...payload,hotel_id:hotel.id,active:true,created_by:user?.auth_user_id||user?.id||null,created_by_name:user?.name||'',created_by_role:user?.role||''},form.photo);setMessage('Promemoria salvato · ntfy priorità 5')}closeForm();await load()}catch(e2){setMessage(e2?.message||(editing?'Modifica non riuscita':'Salvataggio non riuscito'))}finally{setSaving(false)}}
  const toggleActive=async(item)=>{if(!editAllowed)return;try{await updateReminder(item.id,{active:!item.active});await load()}catch(e){setMessage(e?.message||'Aggiornamento non riuscito')}}
  const remove=async(item)=>{if(!deleteAllowed)return;if(!window.confirm('Eliminare questo promemoria?'))return;try{await deleteReminder(item.id);if(editing?.id===item.id)closeForm();await load()}catch(e){setMessage(e?.message||'Eliminazione non riuscita')}}
  if(!allowed)return <EmptyState icon="lock" title="Promemoria">Il tuo ruolo non può creare promemoria.</EmptyState>
  if(loading)return <Spinner label="Carico promemoria…"/>
  return <section data-testid="reminders-view">
    <div className="rs-reminder-head"><div><h1>Promemoria</h1><p>{hotel.name} · {activeCount} attivi · ntfy priorità 5</p></div><Button variant={creating?'ghost':'primary'} icon={creating?'close':'plus'} onClick={()=>creating?closeForm():openNew()}>{creating?'Chiudi':'Nuovo'}</Button></div>
    {message&&<p className="rs-badge rs-badge--accent" style={{display:'inline-flex',margin:'0 0 12px'}}>{message}</p>}
    {creating&&<Card className="rs-card--pad rs-reminder-form-card"><form className="rs-reminder-form" onSubmit={save}>
      <div style={{display:'flex',justifyContent:'space-between',alignItems:'center',gap:10}}><strong>{editing?'Modifica promemoria':'Nuovo promemoria'}</strong>{editing&&<span className="rs-badge rs-badge--accent">Modifica</span>}</div>
      <Field label="Messaggio"><textarea className="rs-textarea" value={form.text} onChange={e=>patch({text:e.target.value})} placeholder="Es. Controllare irrigazione prima di uscire" maxLength={500}/></Field>
      <fieldset className="rs-fieldset"><legend>Destinatari per ruolo</legend><button type="button" className="rs-select rs-reminder-role-picker" onClick={()=>setRolePickerOpen(v=>!v)} aria-expanded={rolePickerOpen}><span>{form.roles.length===0?'Scegli destinatari':allRolesSelected?'Tutti i ruoli':form.roles.length===1?form.roles[0]:`${form.roles.length} ruoli selezionati`}</span><span aria-hidden="true" style={{transform:rolePickerOpen?'rotate(180deg)':'none'}}>⌄</span></button>{rolePickerOpen&&<div className="rs-reminder-role-menu"><button type="button" className={`rs-reminder-role-row ${allRolesSelected?'selected':''}`} onClick={toggleAllRoles}><span><strong>Tutti i ruoli</strong></span><span className="rs-reminder-role-check" aria-hidden="true">{allRolesSelected?'✓':''}</span></button>{ROLES.map(role=>{const selected=form.roles.includes(role);return <button type="button" key={role} className={`rs-reminder-role-row ${selected?'selected':''}`} onClick={()=>toggleRole(role)}><span>{role}</span><span className="rs-reminder-role-check" aria-hidden="true">{selected?'✓':''}</span></button>})}</div>}{form.roles.length>0&&!allRolesSelected&&<div className="rs-reminder-selected">{form.roles.map(role=><button type="button" key={role} className="rs-chip active" onClick={()=>toggleRole(role)}>✓ {role} ×</button>)}</div>}{allRolesSelected&&<div className="rs-reminder-selected"><button type="button" className="rs-chip active" onClick={toggleAllRoles}>✓ Tutti i ruoli ×</button></div>}</fieldset>
      <Field label="Ripetizione"><select className="rs-select" value={form.repeat} onChange={e=>patch({repeat:e.target.value})}><option value="once">Una volta</option><option value="daily">Ogni giorno</option><option value="weekly">Giorni selezionati</option><option value="monthly">Ogni mese</option></select></Field>
      {form.repeat==='weekly'&&<fieldset className="rs-fieldset"><legend>Giorni</legend><div className="rs-chips">{WEEKDAYS.map(([key,label])=><button type="button" key={key} className={`rs-chip ${form.weekdays.includes(key)?'active':''}`} onClick={()=>toggleDay(key)}>{label}</button>)}</div></fieldset>}
      <fieldset className="rs-fieldset"><legend>Orari</legend><div style={{display:'grid',gap:8}}>{form.times.map((time,index)=><div key={index} className="rs-reminder-time-row"><input className="rs-input" type="time" value={time} onChange={e=>setTime(index,e.target.value)}/><Button type="button" variant="ghost" size="sm" icon="trash" onClick={()=>removeTime(index)} disabled={form.times.length===1}>Togli</Button></div>)}</div><Button type="button" variant="ghost" size="sm" icon="plus" onClick={addTime} style={{marginTop:8}}>Aggiungi orario</Button></fieldset>
      <div className="rs-reminder-dates"><Field label="Dal"><input className="rs-input" type="date" value={form.startDate} onChange={e=>patch({startDate:e.target.value})}/></Field><Field label="Fino al (opzionale)"><input className="rs-input" type="date" value={form.endDate} min={form.startDate} onChange={e=>patch({endDate:e.target.value})}/></Field></div>
      <Field label={editing?.photo_path?'Foto':'Foto opzionale'}><div className="rs-reminder-file"><input className="rs-input" type="file" accept="image/*" onChange={e=>patch({photo:e.target.files?.[0]||null,removePhoto:false})}/>{photoPreview&&<div className="rs-reminder-photo-preview"><img src={photoPreview} alt="Anteprima foto promemoria"/><Button type="button" variant="ghost" size="sm" onClick={()=>patch({photo:null})}>Rimuovi nuova foto</Button></div>}{editing?.photo_path&&!form.photo&&!form.removePhoto&&<Button type="button" variant="ghost" size="sm" onClick={()=>patch({removePhoto:true})}>Rimuovi foto attuale</Button>}{form.removePhoto&&<small className="rs-field__hint">La foto attuale verrà rimossa.</small>}{form.photo&&<small className="rs-field__hint">Nuova foto: {form.photo.name}</small>}</div></Field>
      <div className="rs-reminder-form-actions"><Button type="button" variant="ghost" onClick={closeForm}>Annulla</Button><Button variant="primary" disabled={saving}>{saving?'Salvo…':editing?'Salva modifiche':'Salva promemoria'}</Button></div>
    </form></Card>}
    {!items.length?<EmptyState icon="bell" title="Nessun promemoria">Crea il primo promemoria per questa struttura.</EmptyState>:<div style={{display:'grid',gap:10}}>{items.map(item=><Card key={item.id} className="rs-reminder-card"><div className="rs-reminder-card-top"><span className="rs-reminder-icon"><Icon name="bell"/></span><div style={{minWidth:0}}><strong className="rs-reminder-title">{item.message}</strong><div className="rs-reminder-meta"><span>{repeatLabel(item)}</span><span>{(item.times||[]).join(' · ')}</span><span>Dal {item.start_date}{item.end_date?` al ${item.end_date}`:' · senza scadenza'}</span>{item.photo_path&&<span>📷 Foto</span>}</div><div className="rs-reminder-roles">{(item.target_roles||[]).join(', ')}</div>{item.repeat_kind==='weekly'&&<div className="rs-reminder-roles">{(item.weekdays||[]).join(' · ')}</div>}</div><span className={`rs-badge ${item.active?'rs-badge--done':'rs-badge--low'}`}>{item.active?'Attivo':'Pausa'}</span></div>{(editAllowed||deleteAllowed)&&<div className="rs-reminder-actions">{editAllowed&&<><Button variant="ghost" size="sm" icon="edit" onClick={()=>openEdit(item)}>Modifica</Button><Button variant="ghost" size="sm" onClick={()=>toggleActive(item)}>{item.active?'Pausa':'Riattiva'}</Button></>}{deleteAllowed&&<Button variant="danger" size="sm" icon="trash" onClick={()=>remove(item)}>Elimina</Button>}</div>}</Card>)}</div>}
  </section>
}
