import { useState } from 'react'
import { Icon } from '../ui.jsx'

const WD=['Dom','Lun','Mar','Mer','Gio','Ven','Sab']
const MONTHS=['gen','feb','mar','apr','mag','giu','lug','ago','set','ott','nov','dic']
const SHIFTS={mattina:'Mattina',pomeriggio:'Pomeriggio',tutto_giorno:'Giornata intera'}
export const isoDay=(value=new Date())=>{const d=new Date(value);return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}
const addDays=(value,n)=>{const d=new Date(value);d.setDate(d.getDate()+n);return d}
const startOfWeek=(value)=>{const d=new Date(value);const offset=(d.getDay()+6)%7;d.setDate(d.getDate()-offset);d.setHours(12,0,0,0);return d}
const shortDate=(value)=>`${value.getDate()} ${MONTHS[value.getMonth()]}`
export const eventOnDay=(item,date)=>(item.dateFrom||item.date)<=date&&(item.dateTo||item.date)>=date

function Metric({value,label,tone='normal'}){const color=tone==='done'?'var(--rs-ok)':tone==='finish'?'var(--rs-warn)':'var(--rs-text-2)';return <div style={{width:54,height:54,border:'1px solid var(--rs-line)',borderRadius:14,background:'var(--rs-surface-2)',display:'grid',placeItems:'center',alignContent:'center'}}><b style={{fontFamily:'Sora',fontSize:'1.05rem',color}}>{value}</b><small style={{fontSize:'.58rem',color:'var(--rs-text-2)',marginTop:4}}>{label}</small></div>}

export function PlanningChoice({active,icon,title,stats,onClick}){return <button type="button" onClick={onClick} aria-pressed={active} style={{minWidth:0,textAlign:'left',color:'var(--rs-text)',border:`1px solid ${active?'var(--rs-line-strong)':'var(--rs-line)'}`,background:active?'var(--rs-surface-3)':'var(--rs-surface)',borderRadius:18,padding:12,boxShadow:active?'var(--rs-glow)':'var(--rs-shadow)'}}><div style={{display:'flex',alignItems:'center',gap:8,marginBottom:10}}><span style={{width:34,height:34,borderRadius:11,display:'grid',placeItems:'center',background:'var(--rs-surface-2)',color:'var(--rs-cyan)'}}><Icon name={icon}/></span><strong style={{fontFamily:'Sora',fontSize:'.9rem'}}>{title}</strong><span style={{marginLeft:'auto',color:'var(--rs-text-3)'}}>›</span></div><div style={{display:'flex',gap:6,justifyContent:'space-between'}}><Metric value={stats.today} label="Oggi"/><Metric value={stats.finish} label="Da finire" tone="finish"/><Metric value={stats.done} label="Fatti oggi" tone="done"/></div></button>}

export function SaleEventCalendar({bookings}){
  const [anchor,setAnchor]=useState(()=>new Date())
  const today=isoDay(),weekStart=startOfWeek(anchor),days=Array.from({length:7},(_,i)=>addDays(weekStart,i)),weekEnd=days[6]
  return <section style={{border:'1px solid var(--rs-line)',borderRadius:18,padding:14,background:'var(--rs-surface)',display:'grid',gap:12}}>
    <header style={{display:'flex',alignItems:'flex-start',gap:10}}><div style={{minWidth:0,flex:1}}><strong style={{fontFamily:'Sora',fontSize:'1rem'}}>Calendario sale</strong><p style={{margin:'4px 0 0',color:'var(--rs-text-3)',fontSize:'.78rem'}}>Quando le sale sono occupate: qui conta la data dell'evento.</p></div><button type="button" className="rs-btn rs-btn--ghost" onClick={()=>setAnchor(new Date())}>Oggi</button></header>
    <div style={{display:'grid',gridTemplateColumns:'44px minmax(0,1fr) 44px',gap:7,alignItems:'center'}}><button type="button" className="rs-btn rs-btn--ghost" onClick={()=>setAnchor(d=>addDays(d,-7))}>‹</button><div style={{textAlign:'center',fontWeight:800,color:'var(--rs-text-2)'}}>{shortDate(days[0])} – {shortDate(weekEnd)}</div><button type="button" className="rs-btn rs-btn--ghost" onClick={()=>setAnchor(d=>addDays(d,7))}>›</button></div>
    <div style={{display:'grid',gap:7}}>{days.map(day=>{const date=isoDay(day),rows=bookings.filter(b=>eventOnDay(b,date));return <div key={date} style={{display:'grid',gridTemplateColumns:'62px minmax(0,1fr)',gap:8,alignItems:'start'}}><div style={{paddingTop:8,textAlign:'center'}}><strong style={{display:'block',fontSize:'.72rem',color:date===today?'var(--rs-cyan)':'var(--rs-text-2)'}}>{WD[day.getDay()]}</strong><span style={{display:'grid',placeItems:'center',width:34,height:34,margin:'3px auto 0',borderRadius:99,background:date===today?'var(--rs-grad-primary)':'var(--rs-surface-2)',color:date===today?'white':'var(--rs-text)',fontWeight:800}}>{day.getDate()}</span></div><div style={{display:'grid',gap:6,minHeight:50,padding:'6px 0 8px',borderBottom:'1px solid var(--rs-line)'}}>{rows.length?rows.map(b=><article key={`${b.id}-${date}`} style={{border:'1px solid var(--rs-line)',borderLeft:'4px solid var(--rs-cyan)',borderRadius:13,padding:'9px 10px',background:'var(--rs-surface-2)',display:'grid',gap:2}}><div style={{display:'flex',gap:8,alignItems:'baseline'}}><strong style={{minWidth:0,flex:1}}>{b.room}</strong><small style={{color:'var(--rs-text-3)',whiteSpace:'nowrap'}}>{SHIFTS[b.shift]||b.shift}</small></div><span style={{fontSize:'.78rem',color:'var(--rs-text-2)'}}>{b.client}{b.layout?` · ${b.layout}`:''}{b.pax?` · ${b.pax} PAX`:''}</span>{b.dateTo&&b.dateTo!==b.dateFrom&&<small style={{color:'var(--rs-text-3)'}}>Evento {b.dateFrom} → {b.dateTo}</small>}</article>):<span style={{padding:'9px 2px',color:'var(--rs-text-3)',fontSize:'.78rem'}}>Nessuna sala occupata.</span>}</div></div>})}</div>
  </section>
}
