import { useEffect, useState } from 'react'
import { saveSaleRoom, setSaleRoomActive } from '../../sale-config-data.js'
import { Button, Icon, Sheet } from '../ui.jsx'

export default function SaleRoomConfigSheet({open,onClose,hotel,rooms,onSaved}){
  const [editing,setEditing]=useState(null),[draft,setDraft]=useState({name:'',family:'',mode:'simple',selected:[]}),[busy,setBusy]=useState(false),[error,setError]=useState('')
  const active=rooms.filter(r=>r.active),bases=active.filter(r=>r.parts?.length===1&&r.key!==editing?.key)
  const reset=()=>{setEditing(null);setDraft({name:'',family:'',mode:'simple',selected:[]});setError('')}
  useEffect(()=>{if(!open)reset()},[open])
  const edit=r=>{const selected=bases.filter(b=>(b.parts||[]).every(p=>(r.parts||[]).includes(p))).map(b=>b.key);setEditing(r);setDraft({name:r.name,family:r.family||r.name,mode:(r.parts?.length||0)>1?'combo':'simple',selected});setError('')}
  const save=async e=>{e.preventDefault();if(!draft.name.trim()||busy)return;setBusy(true);setError('');try{const key=editing?.key||`room-${globalThis.crypto?.randomUUID?.()||Date.now().toString(36)}`;let parts=editing?.parts||[];if(draft.mode==='simple')parts=editing?.parts?.length===1?editing.parts:[`part:${key}`];else{const chosen=bases.filter(r=>draft.selected.includes(r.key));parts=[...new Set(chosen.flatMap(r=>r.parts||[]))];if(parts.length<2)throw new Error('Seleziona almeno due sale base.')}await saveSaleRoom({hotelId:hotel.id,key,name:draft.name.trim(),family:(draft.family||draft.name).trim(),parts,active:true,sortOrder:editing?.sortOrder??(rooms.length+1)*10});await onSaved();reset()}catch(err){setError(err?.message||'Configurazione non salvata')}finally{setBusy(false)}}
  const toggle=async r=>{setBusy(true);setError('');try{await setSaleRoomActive(hotel.id,r.key,!r.active);await onSaved()}catch(err){setError(err?.message||'Modifica non riuscita')}finally{setBusy(false)}}
  return <Sheet open={open} onClose={onClose} className="rs-sale-sheet"><div style={{display:'grid',gap:14}}><header style={{display:'flex',justifyContent:'space-between',gap:10}}><div><small style={{color:'var(--rs-cyan)',fontWeight:800}}>Direttore Centro Congressi</small><h2 style={{margin:'3px 0 0',fontFamily:'Sora'}}>Configurazione sale</h2></div><button type="button" className="rs-iconbtn" onClick={onClose}><Icon name="close"/></button></header>{rooms.map(r=><div key={r.key} style={{display:'grid',gridTemplateColumns:'1fr auto auto',gap:8,alignItems:'center',padding:10,border:'1px solid var(--rs-line)',borderRadius:13,opacity:r.active?1:.5}}><div><strong>{r.name}</strong><small style={{display:'block',color:'var(--rs-text-3)'}}>{r.family}</small></div><button type="button" className="rs-iconbtn" onClick={()=>edit(r)}><Icon name="edit"/></button><button type="button" className="rs-btn rs-btn--ghost" disabled={busy} onClick={()=>toggle(r)}>{r.active?'Disattiva':'Attiva'}</button></div>)}<form onSubmit={save} style={{display:'grid',gap:10,borderTop:'1px solid var(--rs-line)',paddingTop:12}}><strong>{editing?'Modifica sala':'Aggiungi sala'}</strong><label className="rs-field"><span className="rs-field__label">Nome *</span><input value={draft.name} onChange={e=>setDraft({...draft,name:e.target.value})}/></label><label className="rs-field"><span className="rs-field__label">Famiglia</span><input value={draft.family} onChange={e=>setDraft({...draft,family:e.target.value})} placeholder="Trumpet, Sax, Auditorium oppure nome sala"/></label><div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:7}}><button type="button" className={`rs-btn ${draft.mode==='simple'?'rs-btn--primary':'rs-btn--ghost'}`} onClick={()=>setDraft({...draft,mode:'simple',selected:[]})}>Singola</button><button type="button" className={`rs-btn ${draft.mode==='combo'?'rs-btn--primary':'rs-btn--ghost'}`} onClick={()=>setDraft({...draft,mode:'combo'})}>Combinazione</button></div>{draft.mode==='combo'&&<div style={{display:'grid',gridTemplateColumns:'repeat(2,minmax(0,1fr))',gap:7}}>{bases.map(r=><button type="button" key={r.key} className={`rs-btn ${draft.selected.includes(r.key)?'rs-btn--primary':'rs-btn--ghost'}`} onClick={()=>setDraft({...draft,selected:draft.selected.includes(r.key)?draft.selected.filter(k=>k!==r.key):[...draft.selected,r.key]})}>{r.name}</button>)}</div>}{error&&<p style={{color:'#e35d6a',margin:0}}>{error}</p>}<Button type="submit" variant="primary" disabled={busy||!draft.name.trim()}>{busy?'Salvo…':'Salva'}</Button></form></div></Sheet>
}
