import { useState } from 'react'
import { updateBookingRow } from '../../sale-data.js'
import { Icon, Sheet } from '../ui.jsx'
import { SHIFTS, canManageSalePlanning, norm } from './sale-utils.js'

function AvCheckSheet({booking,user,type,onClose,onRefresh}){
  const isAudio=type==='audio',label=isAudio?'Audio':'Video',icon=isAudio?'🔊':'📽',status=isAudio?booking.audioStatus:booking.videoStatus,required=isAudio?booking.audioRequired:booking.videoRequired
  const [busy,setBusy]=useState(false)
  const save=async next=>{setBusy(true);try{const now=Date.now(),patch=isAudio?{audioRequired:next!=='not_required',audioStatus:next,audioCheckedBy:next==='ok'||next==='problem'?user.name:null,audioCheckedAt:next==='ok'||next==='problem'?now:null}:{videoRequired:next!=='not_required',videoStatus:next,videoCheckedBy:next==='ok'||next==='problem'?user.name:null,videoCheckedAt:next==='ok'||next==='problem'?now:null};await updateBookingRow(booking.id,{...patch,hotelId:booking.hotelId});await onRefresh();onClose()}finally{setBusy(false)}}
  return <Sheet open onClose={onClose} className="rs-sale-sheet"><div style={{display:'grid',gap:14}}><header style={{display:'flex',justifyContent:'space-between',gap:10}}><div><small style={{color:'var(--rs-cyan)',fontWeight:800}}>CHECK SALA</small><h2 style={{margin:'3px 0 0',fontFamily:'Sora'}}>{icon} Test {label}</h2><small style={{color:'var(--rs-text-3)'}}>{booking.room} · {booking.client}</small></div><button type="button" className="rs-iconbtn" onClick={onClose}><Icon name="close"/></button></header>{isAudio?<div style={{minHeight:150,border:'1px solid var(--rs-line)',borderRadius:16,display:'grid',placeItems:'center',textAlign:'center',padding:18,background:'var(--rs-surface-2)'}}><div><div style={{fontSize:'2rem'}}>🎤</div><strong style={{display:'block',marginTop:8}}>Test audio</strong><small style={{display:'block',marginTop:5,color:'var(--rs-text-3)'}}>Il rilevamento automatico col microfono verrà attivato dopo il test reale dell'impianto.</small></div></div>:<div style={{minHeight:150,border:'1px solid var(--rs-line)',borderRadius:16,display:'grid',placeItems:'center',textAlign:'center',padding:18,background:'var(--rs-surface-2)'}}><div><div style={{fontSize:'2rem'}}>📷</div><strong style={{display:'block',marginTop:8}}>Test video</strong><small style={{display:'block',marginTop:5,color:'var(--rs-text-3)'}}>Pronto per il riconoscimento del desktop Windows proiettato sul telo.</small></div></div>}<div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:8}}><button type="button" className="rs-btn rs-btn--primary" disabled={busy} onClick={()=>save('ok')}>✓ OK</button><button type="button" className="rs-btn rs-btn--ghost" disabled={busy} onClick={()=>save('problem')}>⚠ Problema</button></div><div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:8}}><button type="button" className="rs-btn rs-btn--ghost" disabled={busy} onClick={()=>save('pending')}>Da verificare</button><button type="button" className="rs-btn rs-btn--ghost" disabled={busy} onClick={()=>save('not_required')}>N.R.</button></div><small style={{color:'var(--rs-text-3)'}}>Stato attuale: {required?(status==='ok'?'OK':status==='problem'?'Problema':'Da verificare'):'Non richiesto'}</small></div></Sheet>
}

function CheckPill({icon,label,status,required,onClick}){const state=!required?'N.R.':status==='ok'?'✓ OK':status==='problem'?'⚠ Problema':'Da verificare';const color=!required?'var(--rs-text-3)':status==='ok'?'var(--rs-ok)':status==='problem'?'var(--rs-warn)':'var(--rs-cyan)';return <button type="button" onClick={onClick} style={{display:'flex',alignItems:'center',justifyContent:'space-between',gap:8,minHeight:42,padding:'8px 10px',border:'1px solid var(--rs-line)',borderRadius:12,background:'var(--rs-surface-2)',color:'var(--rs-text)',textAlign:'left'}}><span>{icon} {label}</span><strong style={{fontSize:'.76rem',color}}>{state}</strong></button>}

export default function SaleBookingCard({booking,user,onRefresh,onEdit}){
  const director=canManageSalePlanning(user),canStatus=director||norm(user?.role)==='manutentore',done=booking.status==='done',finish=booking.status==='da_finire'
  const [checkType,setCheckType]=useState(null)
  const checksReady=(!booking.audioRequired||booking.audioStatus==='ok')&&(!booking.videoRequired||booking.videoStatus==='ok')
  const setStatus=async status=>{if(status==='done'&&!checksReady){window.alert('Completa prima i controlli Audio/Video richiesti oppure impostali come N.R.');return}const patch=status==='done'?{status:'done',doneBy:user.name,doneAt:Date.now(),toFinishBy:booking.toFinishBy||null,toFinishAt:booking.toFinishAt||null}:{status:'da_finire',toFinishBy:user.name,toFinishAt:Date.now(),doneBy:null,doneAt:null};await updateBookingRow(booking.id,{...patch,hotelId:booking.hotelId});await onRefresh()}
  const eventRange=booking.dateTo&&booking.dateTo!==booking.dateFrom?`${booking.dateFrom} → ${booking.dateTo}`:booking.dateFrom
  return <><article style={{border:'1px solid var(--rs-line)',background:'var(--rs-surface)',borderRadius:16,padding:12,display:'grid',gap:9}}><div style={{display:'flex',gap:10}}><div style={{minWidth:0,flex:1}}><strong>{booking.room}</strong><span style={{display:'block',color:'var(--rs-text-2)',marginTop:2}}>{booking.client}</span><small style={{display:'block',color:'var(--rs-text-3)',marginTop:3}}>{SHIFTS[booking.shift]} · {booking.layout||'—'} · {booking.pax||'—'} PAX</small><small style={{display:'block',color:'var(--rs-cyan)',marginTop:4,fontWeight:750}}>Evento: {eventRange}</small>{booking.notes&&<small style={{display:'block',marginTop:4,color:'var(--rs-text-2)'}}>{booking.notes}</small>}{finish&&<small style={{display:'block',color:'var(--rs-warn)',fontWeight:800,marginTop:4}}>Da finire · {booking.toFinishBy}</small>}{done&&<small style={{display:'block',color:'var(--rs-ok)',fontWeight:800,marginTop:4}}>✓ Fatto da {booking.doneBy}</small>}</div>{director&&<button type="button" className="rs-iconbtn" onClick={()=>onEdit(booking)}><Icon name="edit"/></button>}</div><div style={{display:'grid',gap:6,paddingTop:2}}><small style={{fontWeight:800,color:'var(--rs-text-2)'}}>CHECK SALA</small><div style={{display:'grid',gridTemplateColumns:'repeat(2,minmax(0,1fr))',gap:7}}><CheckPill icon="🔊" label="Audio" required={booking.audioRequired} status={booking.audioStatus} onClick={()=>setCheckType('audio')}/><CheckPill icon="📽" label="Video" required={booking.videoRequired} status={booking.videoStatus} onClick={()=>setCheckType('video')}/></div></div>{canStatus&&!done&&<div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:8}}><button type="button" className="rs-btn rs-btn--ghost" onClick={()=>setStatus('da_finire')}>◐ Da finire</button><button type="button" className="rs-btn rs-btn--primary" onClick={()=>setStatus('done')}>✓ Fatto</button></div>}</article>{checkType&&<AvCheckSheet booking={booking} user={user} type={checkType} onClose={()=>setCheckType(null)} onRefresh={onRefresh}/>}</>
}
