import { supabase } from './supabase.js'
import { cacheRemoteCollection, enqueueMutation, getCachedCollection, isTransientNetworkError, makeClientMutationId, makeOfflineId, registerOfflineHandler } from './offline-store.js'
import { operationFailed, operationSaved } from './operation-feedback.js'

const ENTITY='feedback'
const onlineNow=()=>typeof navigator==='undefined'||navigator.onLine
const fromRow=(row)=>({id:row.id,hotelId:row.hotel_id,userName:row.utente,text:row.testo,createdAt:row.creato_il?new Date(row.creato_il).getTime():Date.now(),clientMutationId:row.mutation_id||null})
async function dbInsert(item){const mutationId=item.clientMutationId||makeClientMutationId();let{data,error}=await supabase.from('feedback').insert({hotel_id:item.hotelId,utente:item.userName,testo:item.text,mutation_id:mutationId}).select().single();if(error?.code==='23505'&&mutationId){const found=await supabase.from('feedback').select('*').eq('mutation_id',mutationId).maybeSingle();data=found.data;error=found.error}if(error)throw error;return fromRow(data)}
registerOfflineHandler(ENTITY,async(op)=>dbInsert(op.payload))
export async function insertFeedback(hotelId,userName,text){const item={hotelId,userName,text,createdAt:Date.now(),clientMutationId:makeClientMutationId()};if(!supabase||!onlineNow()){const tempId=makeOfflineId('offline-feedback');return enqueueMutation({entity:ENTITY,hotelId,action:'create',payload:item,tempId})}try{const created=await dbInsert(item);await cacheRemoteCollection(ENTITY,hotelId,[created,...(await getCachedCollection(ENTITY,hotelId)).filter(x=>x.id!==created.id)]);operationSaved('Feedback inviato');return created}catch(error){if(isTransientNetworkError(error)){const tempId=makeOfflineId('offline-feedback');return enqueueMutation({entity:ENTITY,hotelId,action:'create',payload:item,tempId})}operationFailed(error,'Feedback non inviato');throw error}}
export async function fetchFeedback(hotelId){if(!supabase||!onlineNow())return{items:await getCachedCollection(ENTITY,hotelId),ok:false,offline:true};try{const{data,error}=await supabase.from('feedback').select('*').eq('hotel_id',hotelId).order('creato_il',{ascending:false});if(error)throw error;return{items:await cacheRemoteCollection(ENTITY,hotelId,(data||[]).map(fromRow)),ok:true}}catch(error){return{items:await getCachedCollection(ENTITY,hotelId),ok:false,offline:isTransientNetworkError(error),error:error?.message}}}
export function subscribeFeedback(hotelId,onChange){const onOffline=(event)=>{if(event.detail?.entity===ENTITY&&event.detail?.hotelId===hotelId)onChange({eventType:'OFFLINE_SYNC'})};if(typeof window!=='undefined')window.addEventListener('apice-offline-data-changed',onOffline);let channel=null;if(supabase)channel=supabase.channel('apice-feedback-'+hotelId).on('postgres_changes',{event:'*',schema:'public',table:'feedback',filter:`hotel_id=eq.${hotelId}`},onChange).subscribe();return()=>{if(channel)supabase.removeChannel(channel);if(typeof window!=='undefined')window.removeEventListener('apice-offline-data-changed',onOffline)}}
