import { supabase } from './supabase.js'
import { cacheRemoteCollection, enqueueMutation, getCachedCollection, isTransientNetworkError, makeOfflineId, registerOfflineHandler } from './offline-store.js'

const ENTITY='issues'
function labelDate(iso){if(!iso)return'';const d=new Date(iso),oggi=new Date(),ieri=new Date();ieri.setDate(oggi.getDate()-1);const ora=d.toLocaleTimeString('it-IT',{hour:'2-digit',minute:'2-digit'});if(d.toDateString()===oggi.toDateString())return`Oggi, ${ora}`;if(d.toDateString()===ieri.toDateString())return`Ieri, ${ora}`;return`${d.toLocaleDateString('it-IT',{day:'2-digit',month:'2-digit'})}, ${ora}`}
export function fromRow(row){return{id:row.id,hotelId:row.hotel_id,room:row.camera,urgency:row.urgenza,category:row.categoria,status:row.stato,roomStatus:row.stato_camera||null,title:row.note,photoData:row.foto_prima||null,completionPhotoData:row.foto_dopo||null,createdByName:row.creato_da||null,createdAt:row.creato_il?new Date(row.creato_il).getTime():null,date:labelDate(row.creato_il),completedBy:row.completato_da||null,completedAt:row.completato_il?new Date(row.completato_il).getTime():null,completionNote:row.nota_completamento||null,pieceName:row.pezzo_nome||null,pieceDecision:row.pezzo_decisione||null,pieceDecisionBy:row.pezzo_decisione_da||null,pieceReplaced:row.pezzo_sostituito||null,pieceReplacedBy:row.pezzo_sostituito_da||null,technicianRequestedBy:row.tecnico_richiesto_da||null,technicianId:row.tecnico_id||null,technicianName:row.tecnico_nome||null,technicianPhone:row.tecnico_telefono||null,technicianExpectedArrival:row.tecnico_arrivo_previsto?new Date(row.tecnico_arrivo_previsto).getTime():null,origin:row.origine||'App',department:row.reparto||null}}
function toRow(issue){const row={},set=(c,v)=>{if(v!==undefined)row[c]=v};set('hotel_id',issue.hotelId);set('camera',issue.room);set('urgenza',issue.urgency);set('categoria',issue.category);set('stato',issue.status);set('stato_camera',issue.roomStatus);set('note',issue.title);set('foto_prima',issue.photoData);set('foto_dopo',issue.completionPhotoData);set('creato_da',issue.createdByName);set('completato_da',issue.completedBy);set('nota_completamento',issue.completionNote);set('pezzo_nome',issue.pieceName);set('pezzo_decisione',issue.pieceDecision);set('pezzo_decisione_da',issue.pieceDecisionBy);set('pezzo_sostituito',issue.pieceReplaced);set('pezzo_sostituito_da',issue.pieceReplacedBy);set('tecnico_richiesto_da',issue.technicianRequestedBy);set('tecnico_id',issue.technicianId);set('tecnico_nome',issue.technicianName);set('tecnico_telefono',issue.technicianPhone);if(issue.technicianExpectedArrival!==undefined)row.tecnico_arrivo_previsto=issue.technicianExpectedArrival?new Date(issue.technicianExpectedArrival).toISOString():null;set('origine',issue.origin);set('reparto',issue.department);if(issue.status==='done'&&issue.completedAt)row.completato_il=new Date(issue.completedAt).toISOString();if(issue.status==='tecnico'&&issue.technicianRequestedBy)row.tecnico_richiesto_il=new Date().toISOString();return row}
async function dbInsert(item){const{data,error}=await supabase.from('segnalazioni').insert(toRow(item)).select().single();if(error)throw error;return fromRow(data)}
async function dbUpdate(id,changes){const{data,error}=await supabase.from('segnalazioni').update(toRow(changes)).eq('id',id).select().single();if(error)throw error;return fromRow(data)}
async function dbDelete(id){const{error}=await supabase.from('segnalazioni').delete().eq('id',id);if(error)throw error;return true}
registerOfflineHandler(ENTITY,async(op,targetId)=>op.action==='create'?dbInsert(op.payload):op.action==='update'?dbUpdate(targetId,op.payload):dbDelete(targetId))
export async function fetchIssues(hotelId){if(!supabase||!navigator.onLine)return{issues:await getCachedCollection(ENTITY,hotelId),ok:false,offline:true};try{const{data,error}=await supabase.from('segnalazioni').select('*').eq('hotel_id',hotelId).order('creato_il',{ascending:false});if(error)throw error;return{issues:await cacheRemoteCollection(ENTITY,hotelId,(data||[]).map(fromRow)),ok:true}}catch(error){return{issues:await getCachedCollection(ENTITY,hotelId),ok:false,offline:isTransientNetworkError(error)}}}
export async function insertIssue(issue){if(!supabase||!navigator.onLine){const tempId=makeOfflineId('offline-issue');return enqueueMutation({entity:ENTITY,hotelId:issue.hotelId,action:'create',payload:{...issue,createdAt:issue.createdAt||Date.now()},tempId})}try{return await dbInsert(issue)}catch(error){if(isTransientNetworkError(error)){const tempId=makeOfflineId('offline-issue');return enqueueMutation({entity:ENTITY,hotelId:issue.hotelId,action:'create',payload:{...issue,createdAt:issue.createdAt||Date.now()},tempId})}throw error}}
export async function updateIssueRow(id,changes){const hotelId=changes.hotelId||null;if(!supabase||!navigator.onLine||String(id).startsWith('offline-'))return enqueueMutation({entity:ENTITY,hotelId:hotelId||'unknown',action:'update',payload:changes,targetId:id});try{return await dbUpdate(id,changes)}catch(error){if(isTransientNetworkError(error))return enqueueMutation({entity:ENTITY,hotelId:hotelId||'unknown',action:'update',payload:changes,targetId:id});throw error}}
export async function deleteIssueRow(id,hotelId='unknown'){if(!supabase||!navigator.onLine||String(id).startsWith('offline-'))return enqueueMutation({entity:ENTITY,hotelId,action:'delete',targetId:id});try{return await dbDelete(id)}catch(error){if(isTransientNetworkError(error))return enqueueMutation({entity:ENTITY,hotelId,action:'delete',targetId:id});throw error}}
export function subscribeIssues(hotelId,onChange){if(!supabase)return()=>{};const channel=supabase.channel('apice-segnalazioni-'+hotelId).on('postgres_changes',{event:'*',schema:'public',table:'segnalazioni',filter:`hotel_id=eq.${hotelId}`},onChange).subscribe();return()=>{supabase.removeChannel(channel)}}
