import { supabase } from './supabase.js'
import { cacheRemoteCollection, enqueueMutation, findCachedHotelId, getCachedCollection, isTransientNetworkError, makeOfflineId, registerOfflineHandler } from './offline-store.js'
import { hydratePlannedPhotos, stagePhotoOffline, uploadPhotoValue } from './photo-storage.js'

const ENTITY='planned'
const onlineNow=()=>typeof navigator==='undefined'||navigator.onLine
const isInlinePhoto=(value)=>typeof value==='string'&&value.startsWith('data:image/')
function fromRow(row){return{id:row.id,hotelId:row.hotel_id,location:row.camera,locationMode:row.location_mode||'zona',category:row.categoria,notes:row.note,scheduledAt:row.programmato_dal?new Date(row.programmato_dal).getTime():null,scheduledUntil:row.programmato_al?new Date(row.programmato_al).getTime():null,assignees:row.assegnatari||[],status:row.stato||'pending',rooms:row.camere||null,roomsDone:row.camere_fatte||{},createdBy:row.creato_da,createdAt:row.creato_il?new Date(row.creato_il).getTime():Date.now(),completedBy:row.completato_da||null,completedAt:row.completato_il?new Date(row.completato_il).getTime():null,pieceReplaced:row.pezzo_sostituito||null,photoAfterPath:row.foto_dopo&&!isInlinePhoto(row.foto_dopo)?row.foto_dopo:null,photoAfter:isInlinePhoto(row.foto_dopo)?row.foto_dopo:null,toFinishBy:row.da_finire_da||null,toFinishAt:row.da_finire_il?new Date(row.da_finire_il).getTime():null,technicianExpectedArrival:row.tecnico_arrivo_previsto?new Date(row.tecnico_arrivo_previsto).getTime():null}}
function toRow(item){const row={},set=(c,v)=>{if(v!==undefined)row[c]=v};set('hotel_id',item.hotelId);set('camera',item.location);set('location_mode',item.locationMode);set('categoria',item.category);set('note',item.notes);if(item.scheduledAt!==undefined)row.programmato_dal=item.scheduledAt?new Date(item.scheduledAt).toISOString():null;if(item.scheduledUntil!==undefined)row.programmato_al=item.scheduledUntil?new Date(item.scheduledUntil).toISOString():null;set('assegnatari',item.assignees);set('stato',item.status);set('camere',item.rooms);set('camere_fatte',item.roomsDone);set('creato_da',item.createdBy);set('completato_da',item.completedBy);set('pezzo_sostituito',item.pieceReplaced);set('foto_dopo',item.photoAfterPath!==undefined?item.photoAfterPath:item.photoAfter);set('da_finire_da',item.toFinishBy);if(item.toFinishAt!==undefined)row.da_finire_il=item.toFinishAt?new Date(item.toFinishAt).toISOString():null;if(item.technicianExpectedArrival!==undefined)row.tecnico_arrivo_previsto=item.technicianExpectedArrival?new Date(item.technicianExpectedArrival).toISOString():null;if(item.status==='done'&&item.completedAt)row.completato_il=new Date(item.completedAt).toISOString();return row}
async function prepareForUpload(item){const next={...item};if(item.photoAfter){next.photoAfterPath=await uploadPhotoValue(item.photoAfter,{hotelId:item.hotelId,entity:'planned',kind:'after'});delete next.photoAfter}return next}
async function stageForOffline(item){const queued={...item};if(item.photoAfter)queued.photoAfter=await stagePhotoOffline(item.photoAfter,{hotelId:item.hotelId,entity:'planned',kind:'after'});return queued}
async function dbInsert(item){const prepared=await prepareForUpload(item);const{data,error}=await supabase.from('interventi').insert(toRow(prepared)).select().single();if(error)throw error;return hydratePlannedPhotos(fromRow(data))}
async function dbUpdate(id,changes){const prepared=await prepareForUpload(changes);const{data,error}=await supabase.from('interventi').update(toRow(prepared)).eq('id',id).select().single();if(error)throw error;return hydratePlannedPhotos(fromRow(data))}
async function dbDelete(id){const{error}=await supabase.from('interventi').delete().eq('id',id);if(error)throw error;return true}
registerOfflineHandler(ENTITY,async(op,targetId)=>op.action==='create'?dbInsert(op.payload):op.action==='update'?dbUpdate(targetId,{...op.payload,hotelId:op.hotelId}):dbDelete(targetId))
export async function fetchPlanned(hotelId){if(!supabase||!onlineNow())return{items:await getCachedCollection(ENTITY,hotelId),ok:false,offline:true};try{const{data,error}=await supabase.from('interventi').select('*').eq('hotel_id',hotelId).order('creato_il',{ascending:false});if(error)throw error;const hydrated=await Promise.all((data||[]).map((row)=>hydratePlannedPhotos(fromRow(row))));return{items:await cacheRemoteCollection(ENTITY,hotelId,hydrated),ok:true}}catch(error){return{items:await getCachedCollection(ENTITY,hotelId),ok:false,offline:isTransientNetworkError(error)}}}
export async function insertPlanned(item){if(!supabase||!onlineNow()){const tempId=makeOfflineId('offline-planned'),payload={...item,createdAt:item.createdAt||Date.now()},queued=await stageForOffline(payload);return enqueueMutation({entity:ENTITY,hotelId:item.hotelId,action:'create',payload:queued,cachePayload:payload,tempId})}try{const created=await dbInsert(item);await cacheRemoteCollection(ENTITY,item.hotelId,[created,...(await getCachedCollection(ENTITY,item.hotelId)).filter(x=>x.id!==created.id)]);return created}catch(error){if(isTransientNetworkError(error)){const tempId=makeOfflineId('offline-planned'),payload={...item,createdAt:item.createdAt||Date.now()},queued=await stageForOffline(payload);return enqueueMutation({entity:ENTITY,hotelId:item.hotelId,action:'create',payload:queued,cachePayload:payload,tempId})}throw error}}
export async function updatePlannedRow(id,changes){const hotelId=changes.hotelId||await findCachedHotelId(ENTITY,id);if(!supabase||!onlineNow()||String(id).startsWith('offline-')){const queued=await stageForOffline({...changes,hotelId});return enqueueMutation({entity:ENTITY,hotelId,action:'update',payload:queued,cachePayload:changes,targetId:id})}try{const updated=await dbUpdate(id,{...changes,hotelId});const cached=await getCachedCollection(ENTITY,hotelId);await cacheRemoteCollection(ENTITY,hotelId,cached.map(item=>item.id===id?updated:item));return updated}catch(error){if(isTransientNetworkError(error)){const queued=await stageForOffline({...changes,hotelId});return enqueueMutation({entity:ENTITY,hotelId,action:'update',payload:queued,cachePayload:changes,targetId:id})}throw error}}
export async function deletePlannedRow(id,hotelId=null){const resolved=hotelId||await findCachedHotelId(ENTITY,id);if(!supabase||!onlineNow()||String(id).startsWith('offline-'))return enqueueMutation({entity:ENTITY,hotelId:resolved,action:'delete',targetId:id});try{const ok=await dbDelete(id);const cached=await getCachedCollection(ENTITY,resolved);await cacheRemoteCollection(ENTITY,resolved,cached.filter(item=>item.id!==id));return ok}catch(error){if(isTransientNetworkError(error))return enqueueMutation({entity:ENTITY,hotelId:resolved,action:'delete',targetId:id});throw error}}
export function subscribePlanned(hotelId,onChange){if(!supabase)return()=>{};const channel=supabase.channel('apice-interventi-'+hotelId).on('postgres_changes',{event:'*',schema:'public',table:'interventi',filter:`hotel_id=eq.${hotelId}`},onChange).subscribe();return()=>{supabase.removeChannel(channel)}}
