import { supabase } from './supabase.js'
import { cacheRemoteCollection, enqueueMutation, findCachedHotelId, getCachedCollection, isTransientNetworkError, makeClientMutationId, makeOfflineId, registerOfflineHandler } from './offline-store.js'
import { operationFailed, operationSaved } from './operation-feedback.js'

const ENTITY='sale-bookings'
const onlineNow=()=>typeof navigator==='undefined'||navigator.onLine
const same=(a,b)=>JSON.stringify(a??null)===JSON.stringify(b??null)
function fromRow(row){return{id:row.id,hotelId:row.hotel_id,room:row.sala,dateFrom:row.data,dateTo:row.data_al||row.data,shift:row.turno,client:row.cliente,notes:row.note||'',status:row.stato||'pending',createdBy:row.creato_da,createdAt:row.creato_il?new Date(row.creato_il).getTime():Date.now(),updatedAt:row.updated_at?new Date(row.updated_at).getTime():null,clientMutationId:row.mutation_id||null,toFinishBy:row.da_finire_da||null,toFinishAt:row.da_finire_il?new Date(row.da_finire_il).getTime():null,doneBy:row.completata_da||null,doneAt:row.completata_il?new Date(row.completata_il).getTime():null}}
function toRow(item){const row={},set=(c,v)=>{if(v!==undefined)row[c]=v};set('hotel_id',item.hotelId);set('mutation_id',item.clientMutationId);set('sala',item.room);set('data',item.dateFrom);set('data_al',item.dateTo);set('turno',item.shift);set('cliente',item.client);set('note',item.notes);set('stato',item.status);set('creato_da',item.createdBy);set('da_finire_da',item.toFinishBy);if(item.toFinishAt!==undefined)row.da_finire_il=item.toFinishAt?new Date(item.toFinishAt).toISOString():null;set('completata_da',item.doneBy);if(item.doneAt!==undefined)row.completata_il=item.doneAt?new Date(item.doneAt).toISOString():null;return row}
async function withSyncBase(id,hotelId,changes){if(String(id).startsWith('offline-'))return changes;const cached=await getCachedCollection(ENTITY,hotelId),base=cached.find((item)=>item.id===id);if(!base?.updatedAt)return changes;const baseValues={};for(const key of Object.keys(changes))if(!key.startsWith('_')&&key!=='hotelId'&&key in base)baseValues[key]=base[key];return{...changes,_syncBaseUpdatedAt:base.updatedAt,_syncBaseValues:baseValues}}
function conflictError(fields){const error=new Error(`Conflitto di sincronizzazione: ${fields.join(', ')}`);error.code='OFFLINE_CONFLICT';error.conflictFields=fields;return error}
async function dbInsert(item){const mutationId=item.clientMutationId||makeClientMutationId();let{data,error}=await supabase.from('prenotazioni_sale').insert(toRow({...item,clientMutationId:mutationId})).select().single();if(error?.code==='23505'&&mutationId){const found=await supabase.from('prenotazioni_sale').select('*').eq('mutation_id',mutationId).maybeSingle();data=found.data;error=found.error}if(error)throw error;return fromRow(data)}
async function dbUpdate(id,changes){if(changes._syncBaseUpdatedAt){const{data:current,error:readError}=await supabase.from('prenotazioni_sale').select('*').eq('id',id).single();if(readError)throw readError;const currentApp=fromRow(current),fields=Object.keys(changes._syncBaseValues||{}).filter((key)=>!same(currentApp[key],changes._syncBaseValues[key]));if(fields.length)throw conflictError(fields)}const{data,error}=await supabase.from('prenotazioni_sale').update(toRow(changes)).eq('id',id).select().single();if(error)throw error;return fromRow(data)}
async function dbDelete(id){const{error}=await supabase.from('prenotazioni_sale').delete().eq('id',id);if(error)throw error;return true}
registerOfflineHandler(ENTITY,async(op,targetId)=>op.action==='create'?dbInsert(op.payload):op.action==='update'?dbUpdate(targetId,{...op.payload,hotelId:op.hotelId}):dbDelete(targetId))
export async function fetchBookings(hotelId){if(!supabase||!onlineNow())return{items:await getCachedCollection(ENTITY,hotelId),ok:false,offline:true};try{const{data,error}=await supabase.from('prenotazioni_sale').select('*').eq('hotel_id',hotelId).order('data',{ascending:true});if(error)throw error;return{items:await cacheRemoteCollection(ENTITY,hotelId,(data||[]).map(fromRow)),ok:true}}catch(error){return{items:await getCachedCollection(ENTITY,hotelId),ok:false,offline:isTransientNetworkError(error),error:error?.message}}}
export async function insertBooking(item){const nextItem={...item,clientMutationId:item.clientMutationId||makeClientMutationId()};if(!supabase||!onlineNow()){const tempId=makeOfflineId('offline-booking');return enqueueMutation({entity:ENTITY,hotelId:nextItem.hotelId,action:'create',payload:{...nextItem,createdAt:nextItem.createdAt||Date.now()},tempId})}try{const created=await dbInsert(nextItem);await cacheRemoteCollection(ENTITY,nextItem.hotelId,[created,...(await getCachedCollection(ENTITY,nextItem.hotelId)).filter(x=>x.id!==created.id)]);operationSaved('Prenotazione sala salvata');return created}catch(error){if(isTransientNetworkError(error)){const tempId=makeOfflineId('offline-booking');return enqueueMutation({entity:ENTITY,hotelId:nextItem.hotelId,action:'create',payload:{...nextItem,createdAt:nextItem.createdAt||Date.now()},tempId})}operationFailed(error,'Prenotazione sala non salvata');throw error}}
export async function updateBookingRow(id,changes){const hotelId=changes.hotelId||await findCachedHotelId(ENTITY,id);if(!supabase||!onlineNow()||String(id).startsWith('offline-')){const based=await withSyncBase(id,hotelId,{...changes,hotelId});return enqueueMutation({entity:ENTITY,hotelId,action:'update',payload:based,cachePayload:changes,targetId:id})}try{const updated=await dbUpdate(id,{...changes,hotelId});const cached=await getCachedCollection(ENTITY,hotelId);await cacheRemoteCollection(ENTITY,hotelId,cached.map(item=>item.id===id?updated:item));operationSaved(changes.status==='done'?'Prenotazione completata':'Prenotazione aggiornata');return updated}catch(error){if(isTransientNetworkError(error)){const based=await withSyncBase(id,hotelId,{...changes,hotelId});return enqueueMutation({entity:ENTITY,hotelId,action:'update',payload:based,cachePayload:changes,targetId:id})}operationFailed(error,'Prenotazione non aggiornata');throw error}}
export async function deleteBookingRow(id,hotelId=null){const resolved=hotelId||await findCachedHotelId(ENTITY,id);if(!supabase||!onlineNow()||String(id).startsWith('offline-'))return enqueueMutation({entity:ENTITY,hotelId:resolved,action:'delete',targetId:id});try{const ok=await dbDelete(id);const cached=await getCachedCollection(ENTITY,resolved);await cacheRemoteCollection(ENTITY,resolved,cached.filter(item=>item.id!==id));operationSaved('Prenotazione eliminata');return ok}catch(error){if(isTransientNetworkError(error))return enqueueMutation({entity:ENTITY,hotelId:resolved,action:'delete',targetId:id});operationFailed(error,'Prenotazione non eliminata');throw error}}
export function subscribeBookings(hotelId,onChange){const onOffline=(event)=>{if(event.detail?.entity===ENTITY&&event.detail?.hotelId===hotelId)onChange()};if(typeof window!=='undefined')window.addEventListener('apice-offline-data-changed',onOffline);let channel=null;if(supabase)channel=supabase.channel('apice-sale-'+hotelId).on('postgres_changes',{event:'*',schema:'public',table:'prenotazioni_sale',filter:`hotel_id=eq.${hotelId}`},onChange).subscribe();return()=>{if(channel)supabase.removeChannel(channel);if(typeof window!=='undefined')window.removeEventListener('apice-offline-data-changed',onOffline)}}
