import { supabase } from './supabase.js'
import { cacheRemoteCollection, enqueueMutation, findCachedHotelId, getCachedCollection, isTransientNetworkError, makeOfflineId, registerOfflineHandler } from './offline-store.js'
import { operationFailed, operationSaved } from './operation-feedback.js'

const ENTITY='urgents'
const onlineNow=()=>typeof navigator==='undefined'||navigator.onLine
const statusToApp={aperta:'aperta',presa:'presa_in_carico',completata:'completata'}
const statusToDb={aperta:'aperta',presa_in_carico:'presa',completata:'completata'}
function fromRow(row){return{id:row.id,hotelId:row.hotel_id,note:row.nota,status:statusToApp[row.stato]||'aperta',createdBy:row.creato_da,createdAt:row.creato_il?new Date(row.creato_il).getTime():Date.now(),takenBy:row.presa_in_carico_da||null,completedBy:row.completata_da||null,transformed:!!row.trasformata_in_segnalazione_id}}
function toRow(item){const row={},set=(c,v)=>{if(v!==undefined)row[c]=v};set('hotel_id',item.hotelId);set('nota',item.note);if(item.status!==undefined)row.stato=statusToDb[item.status]||'aperta';set('creato_da',item.createdBy);set('presa_in_carico_da',item.takenBy);set('completata_da',item.completedBy);if(item.status==='presa_in_carico')row.presa_in_carico_il=new Date().toISOString();if(item.status==='completata')row.completata_il=new Date().toISOString();return row}
async function dbInsert(item){const{data,error}=await supabase.from('richieste_urgenti').insert(toRow(item)).select().single();if(error)throw error;return fromRow(data)}
async function dbUpdate(id,changes){const{data,error}=await supabase.from('richieste_urgenti').update(toRow(changes)).eq('id',id).select().single();if(error)throw error;return fromRow(data)}
registerOfflineHandler(ENTITY,async(op,targetId)=>op.action==='create'?dbInsert(op.payload):dbUpdate(targetId,op.payload))
export async function fetchUrgents(hotelId){if(!supabase||!onlineNow())return{items:await getCachedCollection(ENTITY,hotelId),ok:false,offline:true};try{const{data,error}=await supabase.from('richieste_urgenti').select('*').eq('hotel_id',hotelId).order('creato_il',{ascending:false});if(error)throw error;return{items:await cacheRemoteCollection(ENTITY,hotelId,(data||[]).map(fromRow)),ok:true}}catch(error){return{items:await getCachedCollection(ENTITY,hotelId),ok:false,offline:isTransientNetworkError(error),error:error?.message}}}
export async function insertUrgent(item){if(!supabase||!onlineNow()){const tempId=makeOfflineId('offline-urgent');return enqueueMutation({entity:ENTITY,hotelId:item.hotelId,action:'create',payload:{...item,createdAt:item.createdAt||Date.now()},tempId})}try{const created=await dbInsert(item);await cacheRemoteCollection(ENTITY,item.hotelId,[created,...(await getCachedCollection(ENTITY,item.hotelId)).filter(x=>x.id!==created.id)]);operationSaved('Avviso urgente salvato');return created}catch(error){if(isTransientNetworkError(error)){const tempId=makeOfflineId('offline-urgent');return enqueueMutation({entity:ENTITY,hotelId:item.hotelId,action:'create',payload:{...item,createdAt:item.createdAt||Date.now()},tempId})}operationFailed(error,'Avviso urgente non salvato');throw error}}
export async function updateUrgentRow(id,changes){const hotelId=changes.hotelId||await findCachedHotelId(ENTITY,id);if(!supabase||!onlineNow()||String(id).startsWith('offline-'))return enqueueMutation({entity:ENTITY,hotelId,action:'update',payload:changes,targetId:id});try{const updated=await dbUpdate(id,changes);const cached=await getCachedCollection(ENTITY,hotelId);await cacheRemoteCollection(ENTITY,hotelId,cached.map(item=>item.id===id?updated:item));operationSaved(changes.status==='completata'?'Avviso completato':'Avviso aggiornato');return updated}catch(error){if(isTransientNetworkError(error))return enqueueMutation({entity:ENTITY,hotelId,action:'update',payload:changes,targetId:id});operationFailed(error,'Avviso non aggiornato');throw error}}
export function subscribeUrgents(hotelId,onChange){if(!supabase)return()=>{};const channel=supabase.channel('apice-urgenti-'+hotelId).on('postgres_changes',{event:'*',schema:'public',table:'richieste_urgenti',filter:`hotel_id=eq.${hotelId}`},onChange).subscribe();return()=>{supabase.removeChannel(channel)}}
export async function notifyUrgent(hotelId,note){if(!supabase||!onlineNow())return;try{const{data,error}=await supabase.functions.invoke('send-push',{body:{hotel_id:hotelId,title:'Avviso urgente',body:note}});if(error)console.error('notifyUrgent',error);else if(data&&data.ok===false)console.error('notifyUrgent',data.error)}catch(error){console.error('notifyUrgent',error)}}
