-- Punto 8: least privilege, hotel isolation and defense in depth.

-- Urgent audit events are generated by trusted database triggers. Clients may only
-- read events for hotels where they have an active membership.
drop policy if exists urgent_events_insert_authenticated on public.richieste_urgenti_eventi;
drop policy if exists urgent_events_read_authenticated on public.richieste_urgenti_eventi;
create policy urgent_events_member_select
  on public.richieste_urgenti_eventi for select to authenticated
  using (public.is_hotel_member(hotel_id));
revoke all on table public.richieste_urgenti_eventi from anon;
revoke insert, update, delete, truncate, references, trigger on table public.richieste_urgenti_eventi from authenticated;
grant select on table public.richieste_urgenti_eventi to authenticated;

-- Push cryptographic material is service-side only. The browser talks exclusively
-- to push-subscribe, which authenticates the user and uses the service role.
revoke all on table public.push_subscriptions from anon, authenticated;

-- Bearer tokens and WhatsApp integration state are service-side implementation
-- details and must never be directly reachable through PostgREST roles.
revoke all on table public.technician_access_tokens from anon, authenticated;
revoke all on table public.whatsapp_pending_camera from anon, authenticated;
revoke all on table public.whatsapp_template_status from anon, authenticated;

-- Sensor data is visible to members only when mapped to one of their hotels;
-- administrators may inspect all sensors. Only administrators can change mapping.
drop policy if exists sensori_temperatura_authenticated_select on public.sensori_temperatura;
drop policy if exists sensori_temperatura_staff_update on public.sensori_temperatura;
create policy sensori_temperatura_member_select
  on public.sensori_temperatura for select to authenticated
  using (
    exists (
      select 1 from public.hotel_memberships hm
      where hm.auth_user_id = auth.uid() and hm.active
        and (
          hm.can_access_admin
          or (hm.hotel_id = 'gio' and mostra_hotelgio)
          or (hm.hotel_id = 'chocohotel' and mostra_chocohotel)
          or (hm.hotel_id = 'brigantino' and mostra_brigantino)
        )
    )
  );
create policy sensori_temperatura_admin_update
  on public.sensori_temperatura for update to authenticated
  using (exists (select 1 from public.hotel_memberships hm where hm.auth_user_id = auth.uid() and hm.active and hm.can_access_admin))
  with check (exists (select 1 from public.hotel_memberships hm where hm.auth_user_id = auth.uid() and hm.active and hm.can_access_admin));

-- Usage statistics contain cross-hotel aggregates. Keep the RPC available to the
-- administration UI but reject ordinary authenticated users.
create or replace function public.get_usage_stats()
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
begin
  if auth.uid() is null or not exists (
    select 1 from public.hotel_memberships hm
    where hm.auth_user_id = auth.uid() and hm.active and hm.can_access_admin
  ) then
    raise exception 'Non autorizzato' using errcode = '42501';
  end if;
  return (
    select jsonb_build_object(
      'db_size_bytes', pg_database_size(current_database()),
      'db_size_pretty', pg_size_pretty(pg_database_size(current_database())),
      'utenti', (select count(*) from public.utenti),
      'segnalazioni', (select count(*) from public.segnalazioni),
      'interventi', (select count(*) from public.interventi),
      'planning_lavori', (select count(*) from public.planning_lavori),
      'richieste_urgenti', (select count(*) from public.richieste_urgenti),
      'push_subscriptions', (select count(*) from public.push_subscriptions),
      'per_hotel', (
        select jsonb_object_agg(hotel_id, stats) from (
          select h.id as hotel_id, jsonb_build_object(
            'segnalazioni', (select count(*) from public.segnalazioni s where s.hotel_id = h.id),
            'interventi', (select count(*) from public.interventi i where i.hotel_id = h.id),
            'richieste_urgenti', (select count(*) from public.richieste_urgenti r where r.hotel_id = h.id)
          ) as stats from public.hotels h
        ) x
      )
    )
  );
end;
$$;
revoke execute on function public.get_usage_stats() from public, anon;
grant execute on function public.get_usage_stats() to authenticated;

-- Helper used in RLS does not need to be callable anonymously.
revoke execute on function public.has_app_permission(text,text,text) from anon;

-- Trigger helpers should not be exposed as RPCs.
revoke execute on function public.enforce_supremo_permission_rule() from public, anon, authenticated;
revoke execute on function public.set_auth_actor_defaults() from public, anon, authenticated;
revoke execute on function public.set_row_updated_at() from public, anon, authenticated;
revoke execute on function public.set_tecnico_risposta_in_attesa() from public, anon, authenticated;
revoke execute on function public.set_updated_at() from public, anon, authenticated;
