-- Magazzino Blocco 2: QR/barcode, seriali, compatibilita, inventario fisico e trasferimenti.
alter table public.inventory_items add column if not exists catalog_key uuid not null default gen_random_uuid(), add column if not exists scan_code text;
alter table public.inventory_locations add column if not exists scan_code text;
update public.inventory_items set scan_code='RI-'||upper(substr(replace(id::text,'-',''),1,12)) where scan_code is null;
update public.inventory_locations set scan_code='RL-'||upper(substr(replace(id::text,'-',''),1,12)) where scan_code is null;
alter table public.inventory_items alter column scan_code set not null;
alter table public.inventory_locations alter column scan_code set not null;
create unique index if not exists inventory_items_hotel_scan_code_uidx on public.inventory_items(hotel_id,scan_code);
create unique index if not exists inventory_locations_hotel_scan_code_uidx on public.inventory_locations(hotel_id,scan_code);
create index if not exists inventory_items_catalog_key_idx on public.inventory_items(catalog_key);

create table if not exists public.inventory_serial_units(id uuid primary key default gen_random_uuid(),hotel_id text not null,item_id uuid not null,serial_number text not null,asset_tag text not null default ('RA-'||upper(substr(replace(gen_random_uuid()::text,'-',''),1,12))),barcode text,status text not null default 'available' check(status in('available','in_use','maintenance','retired','lost')),location_id uuid,condition text not null default 'ok' check(condition in('ok','attention','damaged')),notes text,active boolean not null default true,created_by uuid default auth.uid(),created_at timestamptz not null default now(),updated_at timestamptz not null default now(),constraint inventory_serial_units_item_hotel_fk foreign key(hotel_id,item_id) references public.inventory_items(hotel_id,id) on delete restrict,constraint inventory_serial_units_location_hotel_fk foreign key(hotel_id,location_id) references public.inventory_locations(hotel_id,id) on delete restrict,unique(hotel_id,serial_number),unique(hotel_id,asset_tag));
create index if not exists inventory_serial_units_item_idx on public.inventory_serial_units(hotel_id,item_id);
create index if not exists inventory_serial_units_location_idx on public.inventory_serial_units(hotel_id,location_id);

create table if not exists public.inventory_compatibility(id uuid primary key default gen_random_uuid(),hotel_id text not null,source_item_id uuid not null,target_item_id uuid not null,relation text not null check(relation in('compatible','equivalent','replaces','accessory','incompatible')),notes text,created_by uuid default auth.uid(),created_at timestamptz not null default now(),constraint inventory_compatibility_source_fk foreign key(hotel_id,source_item_id) references public.inventory_items(hotel_id,id) on delete cascade,constraint inventory_compatibility_target_fk foreign key(hotel_id,target_item_id) references public.inventory_items(hotel_id,id) on delete cascade,constraint inventory_compatibility_not_self check(source_item_id<>target_item_id),unique(hotel_id,source_item_id,target_item_id,relation));
create index if not exists inventory_compatibility_source_idx on public.inventory_compatibility(hotel_id,source_item_id);
create index if not exists inventory_compatibility_target_idx on public.inventory_compatibility(hotel_id,target_item_id);

create table if not exists public.inventory_stocktakes(id uuid primary key default gen_random_uuid(),hotel_id text not null,location_id uuid,status text not null default 'open' check(status in('open','finalized','cancelled')),notes text,opened_by uuid not null default auth.uid(),finalized_by uuid,opened_at timestamptz not null default now(),finalized_at timestamptz,constraint inventory_stocktakes_location_hotel_fk foreign key(hotel_id,location_id) references public.inventory_locations(hotel_id,id) on delete restrict);
create table if not exists public.inventory_stocktake_lines(id uuid primary key default gen_random_uuid(),stocktake_id uuid not null references public.inventory_stocktakes(id) on delete cascade,hotel_id text not null,item_id uuid not null,expected_quantity numeric(12,3) not null check(expected_quantity>=0),counted_quantity numeric(12,3) check(counted_quantity>=0),counted_by uuid,counted_at timestamptz,notes text,constraint inventory_stocktake_lines_item_hotel_fk foreign key(hotel_id,item_id) references public.inventory_items(hotel_id,id) on delete restrict,unique(stocktake_id,item_id));
create index if not exists inventory_stocktake_lines_stocktake_idx on public.inventory_stocktake_lines(stocktake_id);
create index if not exists inventory_stocktakes_hotel_status_idx on public.inventory_stocktakes(hotel_id,status,opened_at desc);

create table if not exists public.inventory_transfers(id uuid primary key default gen_random_uuid(),source_hotel_id text not null,destination_hotel_id text not null,source_item_id uuid not null,destination_item_id uuid,quantity numeric(12,3) not null check(quantity>0),status text not null default 'in_transit' check(status in('in_transit','received','cancelled')),note text,created_by uuid not null default auth.uid(),received_by uuid,created_at timestamptz not null default now(),received_at timestamptz,constraint inventory_transfers_different_hotels check(source_hotel_id<>destination_hotel_id),constraint inventory_transfers_source_item_fk foreign key(source_hotel_id,source_item_id) references public.inventory_items(hotel_id,id) on delete restrict,constraint inventory_transfers_destination_item_fk foreign key(destination_hotel_id,destination_item_id) references public.inventory_items(hotel_id,id) on delete restrict);
create index if not exists inventory_transfers_source_idx on public.inventory_transfers(source_hotel_id,status,created_at desc);
create index if not exists inventory_transfers_destination_idx on public.inventory_transfers(destination_hotel_id,status,created_at desc);

alter table public.inventory_serial_units enable row level security; alter table public.inventory_compatibility enable row level security; alter table public.inventory_stocktakes enable row level security; alter table public.inventory_stocktake_lines enable row level security; alter table public.inventory_transfers enable row level security;
create policy inventory_serial_units_select on public.inventory_serial_units for select to authenticated using((select public.has_app_permission(hotel_id,'inventory','view'))); create policy inventory_serial_units_insert on public.inventory_serial_units for insert to authenticated with check((select public.has_app_permission(hotel_id,'inventory','create'))); create policy inventory_serial_units_update on public.inventory_serial_units for update to authenticated using((select public.has_app_permission(hotel_id,'inventory','edit'))) with check((select public.has_app_permission(hotel_id,'inventory','edit')));
create policy inventory_compatibility_select on public.inventory_compatibility for select to authenticated using((select public.has_app_permission(hotel_id,'inventory','view'))); create policy inventory_compatibility_insert on public.inventory_compatibility for insert to authenticated with check((select public.has_app_permission(hotel_id,'inventory','create'))); create policy inventory_compatibility_update on public.inventory_compatibility for update to authenticated using((select public.has_app_permission(hotel_id,'inventory','edit'))) with check((select public.has_app_permission(hotel_id,'inventory','edit')));
create policy inventory_stocktakes_select on public.inventory_stocktakes for select to authenticated using((select public.has_app_permission(hotel_id,'inventory','view'))); create policy inventory_stocktakes_insert on public.inventory_stocktakes for insert to authenticated with check((select public.has_app_permission(hotel_id,'inventory','create'))); create policy inventory_stocktakes_update on public.inventory_stocktakes for update to authenticated using((select public.has_app_permission(hotel_id,'inventory','edit'))) with check((select public.has_app_permission(hotel_id,'inventory','edit')));
create policy inventory_stocktake_lines_select on public.inventory_stocktake_lines for select to authenticated using((select public.has_app_permission(hotel_id,'inventory','view'))); create policy inventory_stocktake_lines_insert on public.inventory_stocktake_lines for insert to authenticated with check((select public.has_app_permission(hotel_id,'inventory','create'))); create policy inventory_stocktake_lines_update on public.inventory_stocktake_lines for update to authenticated using((select public.has_app_permission(hotel_id,'inventory','edit'))) with check((select public.has_app_permission(hotel_id,'inventory','edit')));
create policy inventory_transfers_select on public.inventory_transfers for select to authenticated using((select public.has_app_permission(source_hotel_id,'inventory','view')) or (select public.has_app_permission(destination_hotel_id,'inventory','view')));

create or replace function public.inventory_open_stocktake(p_hotel_id text,p_location_id uuid default null,p_notes text default null) returns public.inventory_stocktakes language plpgsql security definer set search_path='public','pg_catalog' as $$declare v_take public.inventory_stocktakes;begin if auth.uid() is null or not public.has_app_permission(p_hotel_id,'inventory','edit') then raise exception 'Permesso magazzino non sufficiente';end if;if p_location_id is not null and not exists(select 1 from public.inventory_locations where id=p_location_id and hotel_id=p_hotel_id and active) then raise exception 'Ubicazione non valida';end if;if exists(select 1 from public.inventory_stocktakes where hotel_id=p_hotel_id and status='open' and location_id is not distinct from p_location_id) then raise exception 'Esiste già un inventario aperto per questo ambito';end if;insert into public.inventory_stocktakes(hotel_id,location_id,notes) values(p_hotel_id,p_location_id,nullif(trim(p_notes),'')) returning * into v_take;insert into public.inventory_stocktake_lines(stocktake_id,hotel_id,item_id,expected_quantity) select v_take.id,i.hotel_id,i.id,i.quantity from public.inventory_items i where i.hotel_id=p_hotel_id and i.active and(p_location_id is null or i.default_location_id=p_location_id);return v_take;end$$;
create or replace function public.inventory_count_stocktake_line(p_line_id uuid,p_counted numeric,p_notes text default null) returns public.inventory_stocktake_lines language plpgsql security definer set search_path='public','pg_catalog' as $$declare v_line public.inventory_stocktake_lines;v_status text;begin if p_counted is null or p_counted<0 then raise exception 'Conteggio non valido';end if;select * into v_line from public.inventory_stocktake_lines where id=p_line_id for update;if not found then raise exception 'Riga inventario non disponibile';end if;select status into v_status from public.inventory_stocktakes where id=v_line.stocktake_id;if v_status<>'open' then raise exception 'Inventario non aperto';end if;if auth.uid() is null or not public.has_app_permission(v_line.hotel_id,'inventory','edit') then raise exception 'Permesso magazzino non sufficiente';end if;update public.inventory_stocktake_lines set counted_quantity=p_counted,counted_by=auth.uid(),counted_at=now(),notes=nullif(trim(p_notes),'') where id=p_line_id returning * into v_line;return v_line;end$$;
create or replace function public.inventory_finalize_stocktake(p_stocktake_id uuid) returns public.inventory_stocktakes language plpgsql security definer set search_path='public','pg_catalog' as $$declare v_take public.inventory_stocktakes;r record;v_before numeric(12,3);v_after numeric(12,3);begin select * into v_take from public.inventory_stocktakes where id=p_stocktake_id for update;if not found or v_take.status<>'open' then raise exception 'Inventario non aperto';end if;if auth.uid() is null or not public.has_app_permission(v_take.hotel_id,'inventory','edit') then raise exception 'Permesso magazzino non sufficiente';end if;if exists(select 1 from public.inventory_stocktake_lines where stocktake_id=p_stocktake_id and counted_quantity is null) then raise exception 'Completa tutti i conteggi prima di chiudere';end if;for r in select * from public.inventory_stocktake_lines where stocktake_id=p_stocktake_id loop select quantity into v_before from public.inventory_items where id=r.item_id for update;v_after:=r.counted_quantity;if v_after<>v_before then update public.inventory_items set quantity=v_after,updated_at=now() where id=r.item_id;insert into public.inventory_movements(hotel_id,item_id,delta,quantity_before,quantity_after,movement_type,note,location_id,reason_code,reference_type,reference_id,metadata,created_by) values(v_take.hotel_id,r.item_id,v_after-v_before,v_before,v_after,'inventario','Rettifica da inventario fisico',v_take.location_id,'stocktake','stocktake',p_stocktake_id::text,jsonb_build_object('stocktakeLineId',r.id),auth.uid());end if;end loop;update public.inventory_stocktakes set status='finalized',finalized_by=auth.uid(),finalized_at=now() where id=p_stocktake_id returning * into v_take;return v_take;end$$;
create or replace function public.inventory_start_transfer(p_source_item_id uuid,p_destination_hotel_id text,p_quantity numeric,p_note text default null) returns public.inventory_transfers language plpgsql security definer set search_path='public','pg_catalog' as $$declare v_item public.inventory_items;v_transfer public.inventory_transfers;v_before numeric(12,3);v_after numeric(12,3);begin if p_quantity is null or p_quantity<=0 then raise exception 'Quantità non valida';end if;select * into v_item from public.inventory_items where id=p_source_item_id and active for update;if not found then raise exception 'Articolo non trovato';end if;if v_item.hotel_id=p_destination_hotel_id then raise exception 'La destinazione deve essere un altro hotel';end if;if auth.uid() is null or not public.has_app_permission(v_item.hotel_id,'inventory','edit') then raise exception 'Permesso magazzino sorgente non sufficiente';end if;if not exists(select 1 from public.hotels where id=p_destination_hotel_id and active) then raise exception 'Hotel destinazione non valido';end if;v_before:=v_item.quantity;v_after:=v_before-p_quantity;if v_after<0 then raise exception 'Giacenza insufficiente';end if;insert into public.inventory_transfers(source_hotel_id,destination_hotel_id,source_item_id,quantity,note) values(v_item.hotel_id,p_destination_hotel_id,v_item.id,p_quantity,nullif(trim(p_note),'')) returning * into v_transfer;update public.inventory_items set quantity=v_after,updated_at=now() where id=v_item.id;insert into public.inventory_movements(hotel_id,item_id,delta,quantity_before,quantity_after,movement_type,note,location_id,reason_code,reference_type,reference_id,metadata,created_by) values(v_item.hotel_id,v_item.id,-p_quantity,v_before,v_after,'trasferimento',coalesce(nullif(trim(p_note),''),'Spedito a '||p_destination_hotel_id),v_item.default_location_id,'transfer_out','transfer',v_transfer.id::text,jsonb_build_object('destinationHotelId',p_destination_hotel_id),auth.uid());return v_transfer;end$$;
create or replace function public.inventory_receive_transfer(p_transfer_id uuid) returns public.inventory_transfers language plpgsql security definer set search_path='public','pg_catalog' as $$declare v_t public.inventory_transfers;v_src public.inventory_items;v_dest public.inventory_items;v_category_id uuid;v_before numeric(12,3);begin select * into v_t from public.inventory_transfers where id=p_transfer_id for update;if not found or v_t.status<>'in_transit' then raise exception 'Trasferimento non disponibile';end if;if auth.uid() is null or not public.has_app_permission(v_t.destination_hotel_id,'inventory','edit') then raise exception 'Permesso magazzino destinazione non sufficiente';end if;select * into v_src from public.inventory_items where id=v_t.source_item_id;select * into v_dest from public.inventory_items where hotel_id=v_t.destination_hotel_id and catalog_key=v_src.catalog_key and active order by created_at limit 1 for update;if not found then if v_src.category_id is not null then select dc.id into v_category_id from public.inventory_categories sc join public.inventory_categories dc on dc.code=sc.code and dc.hotel_id=v_t.destination_hotel_id and dc.active where sc.id=v_src.category_id limit 1;end if;insert into public.inventory_items(hotel_id,name,category,category_id,item_type,parent_item_id,variant_label,unit,sku,barcode,manufacturer,model,attributes,tags,synonyms,min_quantity,ideal_quantity,reorder_quantity,notes,catalog_key,quantity) values(v_t.destination_hotel_id,v_src.name,v_src.category,v_category_id,v_src.item_type,null,v_src.variant_label,v_src.unit,v_src.sku,v_src.barcode,v_src.manufacturer,v_src.model,v_src.attributes,v_src.tags,v_src.synonyms,v_src.min_quantity,v_src.ideal_quantity,v_src.reorder_quantity,v_src.notes,v_src.catalog_key,0) returning * into v_dest;end if;v_before:=v_dest.quantity;update public.inventory_items set quantity=quantity+v_t.quantity,updated_at=now() where id=v_dest.id returning * into v_dest;insert into public.inventory_movements(hotel_id,item_id,delta,quantity_before,quantity_after,movement_type,note,location_id,reason_code,reference_type,reference_id,metadata,created_by) values(v_t.destination_hotel_id,v_dest.id,v_t.quantity,v_before,v_dest.quantity,'trasferimento',coalesce(v_t.note,'Ricevuto da '||v_t.source_hotel_id),v_dest.default_location_id,'transfer_in','transfer',v_t.id::text,jsonb_build_object('sourceHotelId',v_t.source_hotel_id),auth.uid());update public.inventory_transfers set status='received',destination_item_id=v_dest.id,received_by=auth.uid(),received_at=now() where id=v_t.id returning * into v_t;return v_t;end$$;
revoke all on function public.inventory_open_stocktake(text,uuid,text),public.inventory_count_stocktake_line(uuid,numeric,text),public.inventory_finalize_stocktake(uuid),public.inventory_start_transfer(uuid,text,numeric,text),public.inventory_receive_transfer(uuid) from public,anon;
grant execute on function public.inventory_open_stocktake(text,uuid,text),public.inventory_count_stocktake_line(uuid,numeric,text),public.inventory_finalize_stocktake(uuid),public.inventory_start_transfer(uuid,text,numeric,text),public.inventory_receive_transfer(uuid) to authenticated;
grant select,insert,update on public.inventory_serial_units,public.inventory_compatibility,public.inventory_stocktakes,public.inventory_stocktake_lines to authenticated;grant select on public.inventory_transfers to authenticated;revoke all on public.inventory_serial_units,public.inventory_compatibility,public.inventory_stocktakes,public.inventory_stocktake_lines,public.inventory_transfers from anon;
