create table if not exists public.randai_documents (
  id uuid primary key default gen_random_uuid(),
  hotel_id text not null references public.hotels(id) on delete cascade,
  equipment_id text references public.randai_equipment(id) on delete set null,
  title text not null,
  source_type text not null check (source_type in ('procedura_interna','manuale_interno','manuale_costruttore','scheda_tecnica')),
  source_label text not null,
  storage_path text,
  version integer not null default 1 check (version > 0),
  status text not null default 'draft' check (status in ('draft','approved','archived')),
  approved_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.randai_document_chunks (
  id bigint generated by default as identity primary key,
  document_id uuid not null references public.randai_documents(id) on delete cascade,
  hotel_id text not null references public.hotels(id) on delete cascade,
  chunk_index integer not null check (chunk_index >= 0),
  heading text,
  content text not null,
  created_at timestamptz not null default now(),
  unique(document_id, chunk_index)
);

create index if not exists randai_documents_hotel_status_idx on public.randai_documents(hotel_id,status,source_type);
create index if not exists randai_document_chunks_hotel_idx on public.randai_document_chunks(hotel_id,document_id);
create index if not exists randai_document_chunks_search_idx on public.randai_document_chunks using gin (to_tsvector('simple', coalesce(heading,'') || ' ' || content));

alter table public.randai_documents enable row level security;
alter table public.randai_document_chunks enable row level security;

drop policy if exists randai_documents_member_read on public.randai_documents;
create policy randai_documents_member_read on public.randai_documents for select to authenticated
using (status='approved' and public.is_hotel_member(hotel_id));

drop policy if exists randai_documents_admin_all on public.randai_documents;
create policy randai_documents_admin_all on public.randai_documents for all to authenticated
using (public.can_admin_hotel(hotel_id)) with check (public.can_admin_hotel(hotel_id));

drop policy if exists randai_chunks_member_read on public.randai_document_chunks;
create policy randai_chunks_member_read on public.randai_document_chunks for select to authenticated
using (public.is_hotel_member(hotel_id) and exists (select 1 from public.randai_documents d where d.id=document_id and d.status='approved'));

drop policy if exists randai_chunks_admin_all on public.randai_document_chunks;
create policy randai_chunks_admin_all on public.randai_document_chunks for all to authenticated
using (public.can_admin_hotel(hotel_id)) with check (public.can_admin_hotel(hotel_id));

create or replace function public.randai_search_document_chunks(p_hotel_id text, p_query text, p_limit integer default 5)
returns table(document_id uuid, title text, source_type text, source_label text, heading text, content text, rank real)
language sql
stable
security definer
set search_path = public
as $$
  select d.id,d.title,d.source_type,d.source_label,c.heading,c.content,
         ts_rank(to_tsvector('simple', coalesce(c.heading,'') || ' ' || c.content), plainto_tsquery('simple', p_query))::real as rank
  from public.randai_document_chunks c
  join public.randai_documents d on d.id=c.document_id and d.hotel_id=c.hotel_id
  where c.hotel_id=p_hotel_id
    and d.status='approved'
    and to_tsvector('simple', coalesce(c.heading,'') || ' ' || c.content) @@ plainto_tsquery('simple', p_query)
  order by rank desc, c.chunk_index asc
  limit greatest(1, least(coalesce(p_limit,5),10));
$$;

revoke all on function public.randai_search_document_chunks(text,text,integer) from public, anon, authenticated;
grant execute on function public.randai_search_document_chunks(text,text,integer) to service_role;
